R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[

	"truck_01_base_f",
	"truck_02_base_f",
 	"truck_03_base_f",
 	"towingtractor",
 	"tractorold",
 	"mtvr",
 	"t810_turrets_base_acr",
 	"b_t_lsv_01_armed_f",
 	"b_t_lsv_01_armed_ctrg_f",
 	"b_lsv_01_armed_f",
 	"b_lsv_01_armed_olive_f",
 	"b_lsv_01_armed_sand_f",
 	"b_lsv_01_armed_black_f",
 	"b_t_lsv_01_armed_olive_f",
 	"b_t_lsv_01_armed_sand_f",
 	"b_t_lsv_01_armed_black_f",
 	"o_t_lsv_02_armed_viper_f",
 	"o_t_lsv_02_armed_f",
 	"o_lsv_02_armed_viper_f",
 	"o_lsv_02_armed_f",
 	"o_t_lsv_02_armed_black_f",
 	"o_t_lsv_02_armed_ghex_f",
 	"o_t_lsv_02_armed_arid_f",
 	"o_lsv_02_armed_black_f",
 	"o_lsv_02_armed_ghex_f",
 	"o_lsv_02_armed_arid_f",
 	"exile_car_offroad_armed_guerilla01",
 	"exile_car_offroad_armed_guerilla02",
 	"exile_car_offroad_armed_guerilla03",
 	"exile_car_offroad_armed_guerilla04",
 	"exile_car_offroad_armed_guerilla05",
 	"exile_car_offroad_armed_guerilla06",
 	"exile_car_offroad_armed_guerilla07",
 	"exile_car_offroad_armed_guerilla08",
 	"exile_car_offroad_armed_guerilla09",
 	"exile_car_offroad_armed_guerilla10",
 	"exile_car_offroad_armed_guerilla11",
 	"exile_car_offroad_armed_guerilla12",
 	"i_g_offroad_01_f",
 	"exile_car_suv_armed_black",
 	"exile_car_btr40_mg_green",
 	"exile_car_btr40_mg_camo",
 	"exile_car_hmmwv_m134_green",
 	"exile_car_hmmwv_m134_desert",
 	"exile_car_hmmwv_m2_green",
 	"exile_car_hmmwv_m2_desert",
 	"cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa",
 	"cup_b_rhib_usmc",
 	"cup_b_rhib2turret_usmc",
 	"b_g_boat_transport_02_f",
 	"o_g_boat_transport_02_f",
 	"i_g_boat_transport_02_f",
 	"i_c_boat_transport_02_f",
 	"c_boat_transport_02_f",
 	"exile_boat_rhib",
 	"exile_boat_motorboat_police",
 	"exile_boat_motorboat_orange",
 	"exile_boat_motorboat_white",
 	"cup_c_fishing_boat_chernarus",
 	"o_boat_armed_01_hmg_f",
 	"i_boat_armed_01_minigun_f",
 	"b_t_boat_armed_01_minigun_f",
 	"b_boat_armed_01_minigun_f",
 	"o_t_boat_armed_01_hmg_f",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_t72_cdf",
 	"cup_b_t72_cz",
 	"cup_b_btr60_cdf",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1129_mc_mk19_desert",
 	"cup_b_m1129_mc_mk19_desert_slat",
 	"cup_b_m1129_mc_mk19_woodland",
 	"cup_b_m1129_mc_mk19_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m270_he_usmc",
 	"cup_b_m270_dpicm_usmc",
 	"cup_b_m270_he_usa",
 	"cup_b_m270_dpicm_usa",
 	"cup_b_m1a1_woodland_us_army",
 	"cup_b_m1a1_woodland_usmc",
 	"cup_b_m1a1_des_usmc",
 	"cup_b_m1a1_des_us_army",
 	"cup_b_m1a2_tusk_mg_us_army",
 	"cup_b_m1a2_tusk_mg_usmc",
 	"cup_b_m1a2_tusk_mg_des_us_army",
 	"cup_b_m1a2_tusk_mg_des_usmc",
 	"cup_b_zsu23_cdf",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_lr_transport_cz_w",
 	"cup_b_lr_transport_cz_d",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_transport_gb_w",
 	"cup_b_lr_transport_gb_d",
 	"cup_b_towingtractor_usmc",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_mtvr_usmc",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_uaz_unarmed_cdf",
 	"cup_b_uaz_open_cdf",
 	"cup_b_uaz_unarmed_acr",
 	"cup_b_uaz_open_acr",
 	"cup_b_ural_cdf",
 	"cup_b_ural_open_cdf",
 	"cup_b_ural_empty_cdf",
 	"cup_b_ural_zu23_cdf",
 	"cup_b_bm21_cdf",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_hmmwv_unarmed_usa",
 	"cup_b_hmmwv_transport_usa",
 	"cup_b_hmmwv_terminal_usa",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_lr_ambulance_cz_w",
 	"cup_b_lr_ambulance_cz_d",
 	"cup_b_lr_ambulance_gb_w",
 	"cup_b_lr_ambulance_gb_d",
 	"cup_b_uh60l_unarmed_ffv_mev_us",
 	"cup_b_mtvr_ammo_usa",
 	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
 	"cup_b_m113_med_usa",
 	"cup_b_hmmwv_ambulance_usmc",
 	"cup_b_hmmwv_ambulance_usa",
 	"cup_b_hmmwv_ambulance_acr",
 	"exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
 	"o_t_mrap_02_hmg_ghex_f",
 	"o_t_mrap_02_gmg_ghex_f",
 	"b_mrap_01_gmg_f",
 	"b_mrap_01_hmg_f",
 	"b_t_mrap_01_gmg_f",
 	"b_t_mrap_01_hmg_f",
 	"i_mrap_03_hmg_f",
 	"i_mrap_03_gmg_f",
 	"cup_b_bmp2_cdf",
 	"o_apc_tracked_02_aa_f",
 	"o_apc_tracked_02_cannon_f",
 	"o_mbt_02_cannon_f",
 	"i_apc_wheeled_03_cannon_f",
 	"i_mbt_03_cannon_f",
 	"i_apc_tracked_03_cannon_f",
 	"b_apc_tracked_01_rcws_f",
 	"b_apc_tracked_01_crv_f",
 	"b_apc_tracked_01_aa_f",
 	"b_mbt_01_cannon_f",
 	"cup_i_t34_napa",
 	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ikarus_blue",
 	"exile_car_ikarus_red",
 	"exile_car_ikarus_party",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"cup_b_mtvr_usa",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_towtractor_white",
 	"exile_car_octavius_white",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_hemmt",
 	"b_truck_01_transport_f",
 	"b_truck_01_covered_f",
 	"b_truck_01_mover_f",
 	"b_truck_01_box_f",
 	"b_truck_01_repair_f",
 	"b_truck_01_ammo_f",
 	"b_truck_01_fuel_f",
 	"b_t_truck_01_mover_f",
 	"b_t_truck_01_ammo_f",
 	"b_t_truck_01_box_f",
 	"b_t_truck_01_fuel_f",
 	"b_t_truck_01_medical_f",
 	"b_t_truck_01_repair_f",
 	"b_t_truck_01_transport_f",
 	"b_t_truck_01_covered_f",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"o_g_offroad_01_f",
 	"i_g_offroad_01_armed_f",
 	"c_van_01_fuel_white_v2_f",
 	"b_t_lsv_01_unarmed_sand_f",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"cup_b_hmmwv_unarmed_usmc",
 	"exile_car_tempest",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"o_truck_02_covered_f",
 	"o_truck_02_transport_f",
 	"i_truck_02_covered_f",
 	"i_truck_02_transport_f",
 	"c_truck_02_transport_f",
 	"o_truck_02_box_f",
 	"o_truck_02_medical_f",
 	"o_truck_02_ammo_f",
 	"o_truck_02_fuel_f",
 	"i_truck_02_box_f",
 	"i_truck_02_medical_f",
 	"i_truck_02_ammo_f",
 	"i_truck_02_fuel_f",
 	"c_truck_02_box_f",
 	"c_truck_02_fuel_f",
 	"c_idap_truck_02_f",
 	"c_idap_truck_02_transport_f",
 	"c_idap_truck_02_water_f",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"
];

LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[

 	"plane",
 	"car_f",
 	"ship_f",
 	"machine_base_f",
 	"d30_base",
 	"m119",
 	"zu23_base",
 	"boat",
 	"pbx_acr",
 	"seafox",
 	"smallboat_1",
 	"exile_container_supplybox",
 	"box_ind_ammoveh_f",
 	"i_cargonet_01_ammo_f",
 	"box_nato_wps_f",
 	"box_nato_ammoord_f",
 	"cup_b_f35b_aa_baf",
 	"cup_b_f35b_cas_baf",
 	"cup_b_f35b_lgb_baf",
 	"cup_b_l39_rkt_cz",
 	"cup_b_l39_bmb_cz",
 	"cup_b_su34_lgb_cdf",
 	"cup_b_su34_agm_cdf",
 	"cup_b_a10_cas_usa",
 	"cup_b_a10_at_usa",
 	"cup_b_av8b_cap_usmc",
 	"cup_b_av8b_gbu12_usmc",
 	"cup_b_av8b_mk82_usmc",
 	"cup_b_av8b_agm_usmc",
 	"cup_b_gr9_cap_gb",
 	"cup_b_gr9_mk82_gb",
 	"cup_b_gr9_gbu12_gb",
 	"cup_b_gr9_agm_gb",
 	"cup_b_su25_cdf",
 	"cup_b_mv22_usmc_rampgun",
 	"cup_b_ah1z_usmc",
 	"cup_b_ah1z_escort_usmc",
 	"cup_b_ah64d_es_usa",
 	"cup_b_aw159_hellfire_gb",
 	"cup_b_aw159_cannon_gb",
 	"cup_b_aw159_hellfire_rn_grey",
 	"cup_b_aw159_cannon_rn_grey",
 	"cup_b_aw159_hellfire_rn_blackcat",
 	"cup_b_aw159_cannon_rn_blackcat",
 	"cup_b_ch47f_usa",
 	"cup_b_ch47f_viv_usa",
 	"cup_b_ch47f_gb",
 	"cup_b_ch47f_viv_gb",
 	"cup_b_mh60s_usmc",
 	"cup_b_mi24_d_cdf",
 	"cup_b_mi35_cz",
 	"cup_b_mi35_cz_des",
 	"cup_b_mi35_cz_ram",
 	"cup_b_mi35_cz_tiger",
 	"cup_b_mi35_cz_dark",
 	"cup_b_mi17_cdf",
 	"cup_b_mi171sh_acr",
 	"cup_b_merlin_hc3_armed_gb",
 	"cup_b_merlin_hc3a_armed_gb",
 	"cup_b_uh1y_gunship_usmc",
 	"exile_chopper_huey_armed_green",
 	"exile_chopper_huey_armed_desert",
 	"cup_b_uh60m_ffv_us",
 	"cup_b_uh60l_ffv_us",
 	"cup_b_ah6j_escort_usa",
 	"cup_b_ah6j_at_usa",
 	"cup_b_ah6j_mp_usa",
 	"cup_b_ah6j_escort19_usa",
 	"b_heli_transport_01_f",
 	"b_heli_transport_01_camo_f",
 	"b_ctrg_heli_transport_01_sand_f",
 	"b_ctrg_heli_transport_01_tropic_f",
 	"cup_i_mi24_mk4_aaf",
 	"cup_o_mi24_mk4_csat_t",
 	"cup_i_mi24_mk4_ion",
 	"cup_i_mi24_mk4_un",
 	"b_heli_attack_01_f",
 	"b_heli_attack_01_dynamicloadout_f",
 	"o_heli_attack_02_f",
 	"o_heli_attack_02_black_f",
 	"o_heli_attack_02_dynamicloadout_f",
 	"b_t_lsv_01_armed_f",
 	"b_t_lsv_01_armed_ctrg_f",
 	"b_lsv_01_armed_f",
 	"b_lsv_01_armed_olive_f",
 	"b_lsv_01_armed_sand_f",
 	"b_lsv_01_armed_black_f",
 	"b_t_lsv_01_armed_olive_f",
 	"b_t_lsv_01_armed_sand_f",
 	"b_t_lsv_01_armed_black_f",
 	"o_t_lsv_02_armed_viper_f",
 	"o_t_lsv_02_armed_f",
 	"o_lsv_02_armed_viper_f",
 	"o_lsv_02_armed_f",
 	"o_t_lsv_02_armed_black_f",
 	"o_t_lsv_02_armed_ghex_f",
 	"o_t_lsv_02_armed_arid_f",
 	"o_lsv_02_armed_black_f",
 	"o_lsv_02_armed_ghex_f",
 	"o_lsv_02_armed_arid_f",
 	"exile_car_offroad_armed_guerilla01",
 	"exile_car_offroad_armed_guerilla02",
 	"exile_car_offroad_armed_guerilla03",
 	"exile_car_offroad_armed_guerilla04",
 	"exile_car_offroad_armed_guerilla05",
 	"exile_car_offroad_armed_guerilla07",
 	"exile_car_offroad_armed_guerilla08",
 	"exile_car_offroad_armed_guerilla09",
 	"exile_car_offroad_armed_guerilla10",
 	"exile_car_offroad_armed_guerilla11",
 	"exile_car_offroad_armed_guerilla12",
 	"i_g_offroad_01_f",
 	"exile_car_suv_armed_black",
 	"exile_car_btr40_mg_green",
 	"exile_car_btr40_mg_camo",
 	"exile_car_hmmwv_m134_green",
 	"exile_car_hmmwv_m134_desert",
 	"exile_car_hmmwv_m2_green",
 	"exile_car_hmmwv_m2_desert",
 	"cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa",
 	"exile_boat_waterscooter",
 	"cup_b_zodiac_usmc",
 	"cup_b_rhib_usmc",
 	"cup_b_rhib2turret_usmc",
 	"b_g_boat_transport_02_f",
 	"o_g_boat_transport_02_f",
 	"i_g_boat_transport_02_f",
 	"i_c_boat_transport_02_f",
 	"c_boat_transport_02_f",
 	"exile_boat_rhib",
 	"exile_boat_sdv_csat",
 	"exile_boat_sdv_digital",
 	"exile_boat_sdv_grey",
 	"exile_boat_rubberduck_csat",
 	"exile_boat_rubberduck_digital",
 	"exile_boat_rubberduck_orange",
 	"exile_boat_rubberduck_blue",
 	"exile_boat_rubberduck_black",
 	"exile_boat_motorboat_police",
 	"exile_boat_motorboat_orange",
 	"exile_boat_motorboat_white",
 	"cup_c_fishing_boat_chernarus",
 	"o_boat_armed_01_hmg_f",
 	"i_boat_armed_01_minigun_f",
 	"b_t_boat_armed_01_minigun_f",
 	"b_boat_armed_01_minigun_f",
 	"o_t_boat_armed_01_hmg_f",
 	"cup_b_c130j_usmc",
 	"cup_b_c130j_cargo_usmc",
 	"cup_b_c130j_gb",
 	"cup_b_c130j_cargo_gb",
 	"cup_b_f35b_aa_usmc",
 	"cup_b_f35b_cas_usmc",
 	"cup_b_f35b_lgb_usmc",
 	"cup_b_l39_cap_cz",
 	"cup_b_uh1d_ger_ksk",
 	"cup_b_uh1d_ger_ksk_des",
 	"cup_b_uh60m_us",
 	"cup_b_uh60l_us",
 	"cup_b_uh60l_unarmed_us",
 	"cup_b_uh60m_unarmed_ffv_us",
 	"cup_b_uh60l_unarmed_ffv_us",
 	"cup_b_mh6j_usa",
 	"cup_b_ah1z_noweapons_usmc",
 	"cup_b_ah1z_at_usmc",
 	"cup_b_ah1z_7rndhydra_usmc",
 	"cup_b_ah1z_14rndhydra_usmc",
 	"cup_b_ah1z_noaa_usmc",
 	"cup_b_ah64d_no_usa",
 	"cup_b_ah64d_at_usa",
 	"cup_b_ah64d_usa",
 	"cup_b_ah64d_mr_usa",
 	"cup_b_aw159_unarmed_gb",
 	"cup_b_wildcat_unarmed_rn_blackcat",
 	"cup_b_mh60s_ffv_usmc",
 	"cup_b_mi6a_cdf",
 	"cup_b_mi6t_cdf",
 	"cup_b_mi17_viv_cdf",
 	"cup_b_mi171sh_unarmed_acr",
 	"cup_b_mv22_viv_usmc",
 	"cup_b_mv22_usmc",
 	"cup_b_ch53e_usmc",
 	"cup_b_ah1_no_baf",
 	"cup_b_ah1_at_baf",
 	"cup_b_ah1_es_baf",
 	"cup_b_ah1_baf",
 	"cup_b_ah1_mr_baf",
 	"cup_b_ch53e_viv_usmc",
 	"cup_b_ch53e_ger",
 	"cup_b_ch53e_viv_ger",
 	"cup_b_c47_usa",
 	"cup_b_ac47_spooky_usa",
 	"cup_b_merlin_hc3_gb",
 	"cup_b_merlin_hc3_viv_gb",
 	"cup_b_merlin_hc3a_gb",
 	"cup_b_merlin_hc4_gb",
 	"cup_b_sa330_puma_hc1_baf",
 	"cup_b_sa330_puma_hc2_baf",
 	"cup_b_uh1y_una_usmc",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_t72_cdf",
 	"cup_b_t72_cz",
 	"cup_b_btr60_cdf",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1129_mc_mk19_desert",
 	"cup_b_m1129_mc_mk19_desert_slat",
 	"cup_b_m1129_mc_mk19_woodland",
 	"cup_b_m1129_mc_mk19_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m270_he_usmc",
 	"cup_b_m270_dpicm_usmc",
 	"cup_b_m270_he_usa",
 	"cup_b_m270_dpicm_usa",
 	"cup_b_m1a1_woodland_us_army",
 	"cup_b_m1a1_woodland_usmc",
 	"cup_b_m1a1_des_usmc",
 	"cup_b_m1a1_des_us_army",
 	"cup_b_m1a2_tusk_mg_us_army",
 	"cup_b_m1a2_tusk_mg_usmc",
 	"cup_b_m1a2_tusk_mg_des_us_army",
 	"cup_b_m1a2_tusk_mg_des_usmc",
 	"cup_b_zsu23_cdf",
 	"cup_b_seafox_usv_usmc",
 	"cup_b_ah6x_usa",
 	"cup_b_usmc_mq9",
 	"cup_b_pchela1t_cdf",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_lr_transport_cz_w",
 	"cup_b_lr_transport_cz_d",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_transport_gb_w",
 	"cup_b_lr_transport_gb_d",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_mtvr_usmc",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_uaz_unarmed_cdf",
 	"cup_b_uaz_open_cdf",
 	"cup_b_uaz_unarmed_acr",
 	"cup_b_uaz_open_acr",
 	"cup_b_ural_cdf",
 	"cup_b_ural_open_cdf",
 	"cup_b_ural_empty_cdf",
 	"cup_b_ural_zu23_cdf",
 	"cup_b_bm21_cdf",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_hmmwv_unarmed_usa",
 	"cup_b_hmmwv_transport_usa",
 	"cup_b_hmmwv_terminal_usa",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_lr_ambulance_cz_w",
 	"cup_b_lr_ambulance_cz_d",
 	"cup_b_lr_ambulance_gb_w",
 	"cup_b_lr_ambulance_gb_d",
 	"cup_b_mtvr_ammo_usa",
 	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
 	"cup_b_mi24_d_mev_cdf",
 	"cup_b_mi17_medevac_cdf",
 	"cup_b_m113_med_usa",
 	"cup_b_hmmwv_ambulance_usmc",
 	"cup_b_hmmwv_ambulance_usa",
 	"cup_b_hmmwv_ambulance_acr",
 	"cup_b_uh1y_mev_usmc",
 	"exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
 	"o_t_mrap_02_hmg_ghex_f",
 	"o_t_mrap_02_gmg_ghex_f",
 	"b_mrap_01_gmg_f",
 	"b_mrap_01_hmg_f",
 	"b_t_mrap_01_gmg_f",
 	"b_t_mrap_01_hmg_f",
 	"i_mrap_03_hmg_f",
 	"i_mrap_03_gmg_f",
 	"i_ugv_01_rcws_f",
 	"cup_b_bmp2_cdf",
 	"o_apc_tracked_02_aa_f",
 	"o_apc_tracked_02_cannon_f",
 	"o_mbt_02_cannon_f",
 	"i_apc_wheeled_03_cannon_f",
 	"i_mbt_03_cannon_f",
 	"i_apc_tracked_03_cannon_f",
 	"b_apc_tracked_01_rcws_f",
 	"b_apc_tracked_01_crv_f",
 	"b_apc_tracked_01_aa_f",
 	"b_mbt_01_cannon_f",
 	"cup_i_t34_napa",
 	"exile_plane_cessna",
 	"exile_plane_an2_green",
 	"exile_plane_an2_white",
 	"exile_plane_an2_stripe",
 	"exile_plane_ceasar",
 	"exile_plane_blackfishinfantry",
 	"exile_plane_blackfishvehicle",
 	"exile_chopper_huey_green",
 	"exile_chopper_hellcat_green",
 	"exile_chopper_hellcat_fia",
 	"exile_chopper_huey_desert",
 	"exile_chopper_hummingbird_green",
 	"exile_chopper_hummingbird_civillian_blue",
 	"exile_chopper_hummingbird_civillian_red",
 	"exile_chopper_hummingbird_civillian_ion",
 	"exile_chopper_hummingbird_civillian_blueline",
 	"exile_chopper_hummingbird_civillian_digital",
 	"exile_chopper_hummingbird_civillian_elliptical",
 	"exile_chopper_hummingbird_civillian_furious",
 	"exile_chopper_hummingbird_civillian_graywatcher",
 	"exile_chopper_hummingbird_civillian_jeans",
 	"exile_chopper_hummingbird_civillian_light",
 	"exile_chopper_hummingbird_civillian_shadow",
 	"exile_chopper_hummingbird_civillian_sheriff",
 	"exile_chopper_hummingbird_civillian_speedy",
 	"exile_chopper_hummingbird_civillian_sunset",
 	"exile_chopper_hummingbird_civillian_vrana",
 	"exile_chopper_hummingbird_civillian_wasp",
 	"exile_chopper_hummingbird_civillian_wave",
 	"exile_chopper_huron_black",
 	"exile_chopper_huron_green",
 	"exile_chopper_mohawk_fia",
 	"exile_chopper_orca_csat",
 	"exile_chopper_orca_black",
 	"exile_chopper_orca_blackcustom",
 	"exile_chopper_taru_transport_csat",
 	"exile_chopper_taru_transport_black",
 	"exile_chopper_taru_csat",
 	"exile_chopper_taru_black",
 	"exile_chopper_taru_covered_csat",
 	"exile_chopper_taru_covered_black",
 	"cup_b_uh60m_unarmed_us",
 	"cup_b_uh60m_unarmed_ffv_mev_us",
 	"exile_bike_quadbike_black",
 	"exile_bike_quadbike_blue",
 	"exile_bike_quadbike_red",
 	"exile_bike_quadbike_white",
 	"exile_bike_quadbike_nato",
 	"exile_bike_quadbike_csat",
 	"exile_bike_quadbike_fia",
 	"exile_bike_quadbike_guerilla01",
 	"exile_bike_quadbike_guerilla02",
 	"exile_car_kart_bluking",
 	"exile_car_kart_redstone",
 	"exile_car_kart_vrana",
 	"exile_car_kart_green",
 	"exile_car_kart_blue",
 	"exile_car_kart_orange",
 	"exile_car_kart_white",
 	"exile_car_kart_yellow",
 	"exile_car_kart_black",
 	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ikarus_blue",
 	"exile_car_ikarus_red",
 	"exile_car_ikarus_party",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"cup_b_mtvr_usa",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_towtractor_white",
 	"cup_b_towingtractor_usmc",
 	"exile_car_octavius_white",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_hemmt",
 	"b_truck_01_transport_f",
 	"b_truck_01_covered_f",
 	"b_truck_01_mover_f",
 	"b_truck_01_box_f",
 	"b_truck_01_repair_f",
 	"b_truck_01_ammo_f",
 	"b_truck_01_fuel_f",
 	"b_t_truck_01_mover_f",
 	"b_t_truck_01_ammo_f",
 	"b_t_truck_01_box_f",
 	"b_t_truck_01_fuel_f",
 	"b_t_truck_01_medical_f",
 	"b_t_truck_01_repair_f",
 	"b_t_truck_01_transport_f",
 	"b_t_truck_01_covered_f",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"o_g_offroad_01_f",
 	"i_g_offroad_01_armed_f",
 	"c_van_01_fuel_white_v2_f",
 	"b_t_lsv_01_unarmed_sand_f",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"cup_b_hmmwv_unarmed_usmc",
 	"exile_car_tempest",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"o_truck_02_covered_f",
 	"o_truck_02_transport_f",
 	"i_truck_02_covered_f",
 	"i_truck_02_transport_f",
 	"c_truck_02_transport_f",
 	"o_truck_02_box_f",
 	"o_truck_02_medical_f",
 	"o_truck_02_ammo_f",
 	"o_truck_02_fuel_f",
 	"i_truck_02_box_f",
 	"i_truck_02_medical_f",
 	"i_truck_02_ammo_f",
 	"i_truck_02_fuel_f",
 	"c_truck_02_box_f",
 	"c_truck_02_fuel_f",
 	"c_idap_truck_02_f",
 	"c_idap_truck_02_transport_f",
 	"c_idap_truck_02_water_f",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[

 	"heli_light_02_base_f",
 	"heli_transport_01_base_f",
 	"heli_transport_02_base_f",
 	"b_heli_transport_03_base_f",
 	"heli_transport_04_base_f",
 	"ah64_base_ep1",
 	"aw159_lynx_baf",
 	"baf_merlin_hc3_d",
 	"ch47_base_ep1",
 	"ka60_base_pmc",
 	"kamov_base",
 	"mi17_base",
 	"mi24_base",
 	"uh1_base",
 	"uh60_base",
 	"heli_light_02_base_f",
 	"heli_transport_01_base_f",
 	"heli_transport_02_base_f",
 	"heli_light_02_base_f",
 	"heli_transport_01_base_f",
 	"heli_transport_02_base_f",
 	"cup_b_aw159_hellfire_gb",
 	"cup_b_aw159_cannon_gb",
 	"cup_b_aw159_hellfire_rn_grey",
 	"cup_b_aw159_cannon_rn_grey",
 	"cup_b_aw159_hellfire_rn_blackcat",
 	"cup_b_aw159_cannon_rn_blackcat",
 	"cup_b_ch47f_usa",
 	"cup_b_ch47f_viv_usa",
 	"cup_b_ch47f_gb",
 	"cup_b_ch47f_viv_gb",
 	"cup_b_mh60s_usmc",
 	"cup_b_mi24_d_cdf",
 	"cup_b_mi35_cz",
 	"cup_b_mi35_cz_des",
 	"cup_b_mi35_cz_ram",
 	"cup_b_mi35_cz_tiger",
 	"cup_b_mi35_cz_dark",
 	"cup_b_mi17_cdf",
 	"cup_b_mi171sh_acr",
 	"cup_b_merlin_hc3_armed_gb",
 	"cup_b_merlin_hc3a_armed_gb",
 	"cup_b_uh1y_gunship_usmc",
 	"exile_chopper_huey_armed_green",
 	"exile_chopper_huey_armed_desert",
 	"cup_b_uh60m_ffv_us",
 	"cup_b_uh60l_ffv_us",
 	"b_heli_transport_01_f",
 	"b_heli_transport_01_camo_f",
 	"b_ctrg_heli_transport_01_sand_f",
 	"b_ctrg_heli_transport_01_tropic_f",
 	"cup_i_mi24_mk4_aaf",
 	"cup_o_mi24_mk4_csat_t",
 	"cup_i_mi24_mk4_ion",
 	"cup_i_mi24_mk4_un",
 	"o_heli_attack_02_f",
 	"o_heli_attack_02_black_f",
 	"o_heli_attack_02_dynamicloadout_f",
 	"cup_b_uh1d_ger_ksk",
 	"cup_b_uh1d_ger_ksk_des",
 	"cup_b_uh60m_us",
 	"cup_b_uh60l_us",
 	"cup_b_uh60m_unarmed_us",
 	"cup_b_uh60l_unarmed_us",
 	"cup_b_uh60m_unarmed_ffv_us",
 	"cup_b_uh60l_unarmed_ffv_us",
 	"cup_b_aw159_unarmed_gb",
 	"cup_b_wildcat_unarmed_rn_blackcat",
 	"cup_b_mh60s_ffv_usmc",
 	"cup_b_mi6a_cdf",
 	"cup_b_mi6t_cdf",
 	"cup_b_mi17_viv_cdf",
 	"cup_b_ch53e_usmc",
 	"cup_b_ch53e_viv_usmc",
 	"cup_b_ch53e_ger",
 	"cup_b_ch53e_viv_ger",
 	"cup_b_merlin_hc3_gb",
 	"cup_b_merlin_hc3_viv_gb",
 	"cup_b_merlin_hc3a_gb",
 	"cup_b_merlin_hc4_gb",
 	"cup_b_sa330_puma_hc1_baf",
 	"cup_b_sa330_puma_hc2_baf",
 	"cup_b_uh1y_una_usmc",
 	"cup_b_uh60l_unarmed_ffv_mev_us",
 	"cup_b_mi24_d_mev_cdf",
 	"cup_b_mi17_medevac_cdf",
 	"cup_b_uh1y_mev_usmc",
 	"exile_chopper_huey_green",
 	"exile_chopper_hellcat_green",
 	"exile_chopper_hellcat_fia",
 	"exile_chopper_huey_desert",
 	"exile_chopper_huron_black",
 	"exile_chopper_huron_green",
 	"exile_chopper_mohawk_fia",
 	"exile_chopper_orca_csat",
 	"exile_chopper_orca_black",
 	"exile_chopper_orca_blackcustom",
 	"exile_chopper_taru_transport_csat",
 	"exile_chopper_taru_transport_black",
 	"exile_chopper_taru_csat",
 	"exile_chopper_taru_black",
 	"exile_chopper_taru_covered_csat",
 	"exile_chopper_taru_covered_black",
	"cup_b_uh60m_unarmed_ffv_mev_us"	
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"bus",
 	"car_f",
 	"ship_f",
 	"b_supplycrate_f",
 	"c_supplycrate_f",
 	"box_east_ammoveh_f",
 	"ig_supplycrate_f",
 	"box_ind_ammoveh_f",
 	"box_nato_ammoveh_f",
 	"cargo_base_f",
 	"land_cargobox_v1_f",
 	"cargo10_base_f",
 	"machine_base_f",
 	"cargonet_01_base_f",
 	"slingload_01_base_f",
 	"atv_base_ep1",
 	"armoredsuv_base_pmc",
 	"baf_jackal2_base_d",
 	"datsun_pk1",
 	"dingo_base_acr",
 	"hilux_pk1",
 	"hmmwv_base",
 	"ikarus",
 	"lada_base",
 	"landrover_base",
 	"octavia_acr",
 	"offroad_dshkm_base",
 	"pickup_pk_base",
 	"s1203_tk_civ_ep1",
 	"suv_base_ep1",
 	"skodabase",
 	"towingtractor",
 	"tractorold",
 	"kamaz_base",
 	"mtvr",
 	"t810_turrets_base_acr",
 	"truck_base_h",
 	"ural_base_withturret",
 	"v3s_base",
 	"uaz_base",
 	"volha_tk_civ_base_ep1",
 	"vwgolf",
 	"btr40_mg_base_ep1",
 	"btr90_base",
 	"gaz_vodnik_hmg",
 	"lav25_base",
 	"strykerbase_ep1",
 	"hilux1_civil_1_open",
 	"d30_base",
 	"m119",
 	"zu23_base",
 	"m113_base",
 	"boat",
 	"seafox",
 	"smallboat_1",
 	"land_misc_cargo1a_ep1",
 	"land_misc_cargo1ao",
 	"land_misc_cargo1ao_ep1",
 	"land_misc_cargo1b",
 	"land_misc_cargo1b_ep1",
 	"land_misc_cargo1bo",
 	"land_misc_cargo1c",
 	"land_misc_cargo1c_ep1",
 	"land_misc_cargo1d",
 	"land_misc_cargo1d_ep1",
 	"land_misc_cargo1e",
 	"land_misc_cargo1e_ep1",
 	"land_misc_cargo1f",
 	"land_misc_cargo1g",
 	"land_misc_cargomarket1a_ep1",
 	"base_warfarebcontructionsite",
 	"misc_cargo_cont_net1",
 	"misc_cargo_cont_small",
 	"misc_cargo_cont_small2",
 	"r3f_uniformbox",
 	"r3f_weaponstock",
 	"exile_container_supplybox",
 	"i_cargonet_01_ammo_f",
 	"box_nato_wps_f",
 	"box_nato_ammoord_f",
 	"cup_b_f35b_aa_baf",
 	"cup_b_f35b_cas_baf",
 	"cup_b_f35b_lgb_baf",
 	"cup_b_l39_rkt_cz",
 	"cup_b_l39_bmb_cz",
 	"cup_b_su34_lgb_cdf",
 	"cup_b_su34_agm_cdf",
 	"cup_b_a10_cas_usa",
 	"cup_b_a10_at_usa",
 	"cup_b_av8b_cap_usmc",
 	"cup_b_av8b_gbu12_usmc",
 	"cup_b_av8b_mk82_usmc",
 	"cup_b_av8b_agm_usmc",
 	"cup_b_gr9_cap_gb",
 	"cup_b_gr9_mk82_gb",
 	"cup_b_gr9_gbu12_gb",
 	"cup_b_gr9_agm_gb",
 	"cup_b_su25_cdf",
 	"cup_b_ah1z_usmc",
 	"cup_b_ah1z_escort_usmc",
 	"cup_b_ah64d_es_usa",
 	"cup_b_aw159_hellfire_gb",
 	"cup_b_aw159_cannon_gb",
 	"cup_b_aw159_hellfire_rn_grey",
 	"cup_b_aw159_cannon_rn_grey",
 	"cup_b_aw159_hellfire_rn_blackcat",
 	"cup_b_aw159_cannon_rn_blackcat",
 	"cup_b_mh60s_usmc",
 	"cup_b_uh1y_gunship_usmc",
 	"exile_chopper_huey_armed_green",
 	"exile_chopper_huey_armed_desert",
 	"cup_b_uh60m_ffv_us",
 	"cup_b_uh60l_ffv_us",
 	"cup_b_ah6j_escort_usa",
 	"cup_b_ah6j_at_usa",
 	"cup_b_ah6j_mp_usa",
 	"cup_b_ah6j_escort19_usa",
 	"b_heli_transport_01_camo_f",
 	"b_ctrg_heli_transport_01_tropic_f",
 	"b_heli_attack_01_f",
 	"b_heli_attack_01_dynamicloadout_f",
 	"b_t_lsv_01_armed_f",
 	"b_t_lsv_01_armed_ctrg_f",
 	"b_lsv_01_armed_f",
 	"b_lsv_01_armed_olive_f",
 	"b_lsv_01_armed_sand_f",
 	"b_lsv_01_armed_black_f",
 	"b_t_lsv_01_armed_olive_f",
 	"b_t_lsv_01_armed_sand_f",
 	"b_t_lsv_01_armed_black_f",
 	"o_t_lsv_02_armed_viper_f",
 	"o_t_lsv_02_armed_f",
 	"o_lsv_02_armed_viper_f",
 	"o_lsv_02_armed_f",
 	"o_t_lsv_02_armed_black_f",
 	"o_t_lsv_02_armed_ghex_f",
 	"o_t_lsv_02_armed_arid_f",
 	"o_lsv_02_armed_black_f",
 	"o_lsv_02_armed_ghex_f",
 	"o_lsv_02_armed_arid_f",
 	"exile_car_offroad_armed_guerilla01",
 	"exile_car_offroad_armed_guerilla02",
 	"exile_car_offroad_armed_guerilla03",
 	"exile_car_offroad_armed_guerilla04",
 	"exile_car_offroad_armed_guerilla05",
 	"exile_car_offroad_armed_guerilla06",
 	"exile_car_offroad_armed_guerilla07",
 	"exile_car_offroad_armed_guerilla08",
 	"exile_car_offroad_armed_guerilla09",
 	"exile_car_offroad_armed_guerilla10",
 	"exile_car_offroad_armed_guerilla11",
 	"exile_car_offroad_armed_guerilla12",
 	"i_g_offroad_01_f",
 	"exile_car_suv_armed_black",
 	"exile_car_btr40_mg_green",
 	"exile_car_btr40_mg_camo",
 	"exile_car_hmmwv_m134_green",
 	"exile_car_hmmwv_m134_desert",
 	"exile_car_hmmwv_m2_green",
 	"exile_car_hmmwv_m2_desert",
 	"cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa",
 	"exile_boat_waterscooter",
 	"cup_b_zodiac_usmc",
 	"cup_b_rhib_usmc",
 	"cup_b_rhib2turret_usmc",
 	"b_g_boat_transport_02_f",
 	"o_g_boat_transport_02_f",
 	"i_g_boat_transport_02_f",
 	"i_c_boat_transport_02_f",
 	"c_boat_transport_02_f",
 	"exile_boat_rhib",
 	"exile_boat_sdv_csat",
 	"exile_boat_sdv_digital",
 	"exile_boat_sdv_grey",
 	"exile_boat_rubberduck_csat",
 	"exile_boat_rubberduck_digital",
 	"exile_boat_rubberduck_orange",
 	"exile_boat_rubberduck_blue",
 	"exile_boat_rubberduck_black",
 	"exile_boat_motorboat_police",
 	"exile_boat_motorboat_orange",
 	"exile_boat_motorboat_white",
 	"cup_c_fishing_boat_chernarus",
 	"o_boat_armed_01_hmg_f",
 	"i_boat_armed_01_minigun_f",
 	"b_t_boat_armed_01_minigun_f",
 	"b_boat_armed_01_minigun_f",
 	"o_t_boat_armed_01_hmg_f",
 	"cup_b_f35b_aa_usmc",
 	"cup_b_f35b_cas_usmc",
 	"cup_b_f35b_lgb_usmc",
 	"cup_b_l39_cap_cz",
 	"cup_b_uh1d_ger_ksk",
 	"cup_b_uh1d_ger_ksk_des",
 	"cup_b_uh60m_us",
 	"cup_b_uh60l_us",
 	"cup_b_mh6j_usa",
 	"cup_b_ah1z_noweapons_usmc",
 	"cup_b_ah1z_at_usmc",
 	"cup_b_ah1z_7rndhydra_usmc",
 	"cup_b_ah1z_14rndhydra_usmc",
 	"cup_b_ah1z_noaa_usmc",
 	"cup_b_ah64d_no_usa",
 	"cup_b_ah64d_at_usa",
 	"cup_b_ah64d_usa",
 	"cup_b_ah64d_mr_usa",
 	"cup_b_aw159_unarmed_gb",
 	"cup_b_wildcat_unarmed_rn_blackcat",
 	"cup_b_mh60s_ffv_usmc",
 	"cup_b_mi171sh_unarmed_acr",
 	"cup_b_ah1_no_baf",
 	"cup_b_ah1_at_baf",
 	"cup_b_ah1_es_baf",
 	"cup_b_ah1_baf",
 	"cup_b_ah1_mr_baf",
 	"cup_b_uh1y_una_usmc",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_btr60_cdf",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1129_mc_mk19_desert",
 	"cup_b_m1129_mc_mk19_desert_slat",
 	"cup_b_m1129_mc_mk19_woodland",
 	"cup_b_m1129_mc_mk19_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m270_he_usmc",
 	"cup_b_m270_dpicm_usmc",
 	"cup_b_m270_he_usa",
 	"cup_b_m270_dpicm_usa",
 	"cup_b_zsu23_cdf",
 	"cup_b_seafox_usv_usmc",
 	"cup_b_ah6x_usa",
 	"cup_b_usmc_mq9",
 	"cup_b_pchela1t_cdf",
 	"cup_b_m1030",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_lr_transport_cz_w",
 	"cup_b_lr_transport_cz_d",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_transport_gb_w",
 	"cup_b_lr_transport_gb_d",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_mtvr_usmc",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_uaz_unarmed_cdf",
 	"cup_b_uaz_open_cdf",
 	"cup_b_uaz_unarmed_acr",
 	"cup_b_uaz_open_acr",
 	"cup_b_ural_cdf",
 	"cup_b_ural_open_cdf",
 	"cup_b_ural_empty_cdf",
 	"cup_b_ural_zu23_cdf",
 	"cup_b_bm21_cdf",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_hmmwv_unarmed_usa",
 	"cup_b_hmmwv_transport_usa",
 	"cup_b_hmmwv_terminal_usa",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_lr_ambulance_cz_w",
 	"cup_b_lr_ambulance_cz_d",
 	"cup_b_lr_ambulance_gb_w",
 	"cup_b_lr_ambulance_gb_d",
 	"cup_b_mtvr_ammo_usa",
 	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
 	"cup_b_m113_med_usa",
 	"cup_b_hmmwv_ambulance_usmc",
 	"cup_b_hmmwv_ambulance_usa",
 	"cup_b_hmmwv_ambulance_acr",
 	"cup_b_uh1y_mev_usmc",
 	"exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
 	"o_t_mrap_02_hmg_ghex_f",
 	"o_t_mrap_02_gmg_ghex_f",
 	"b_mrap_01_gmg_f",
 	"b_mrap_01_hmg_f",
 	"b_t_mrap_01_gmg_f",
 	"b_t_mrap_01_hmg_f",
 	"i_mrap_03_hmg_f",
 	"i_mrap_03_gmg_f",
 	"i_ugv_01_rcws_f",
 	"cup_b_bmp2_cdf",
 	"o_apc_tracked_02_aa_f",
 	"o_apc_tracked_02_cannon_f",
 	"i_apc_wheeled_03_cannon_f",
 	"i_apc_tracked_03_cannon_f",
 	"b_apc_tracked_01_rcws_f",
 	"b_apc_tracked_01_crv_f",
 	"b_apc_tracked_01_aa_f",
 	"exile_chopper_huey_green",
 	"exile_chopper_hellcat_green",
 	"exile_chopper_hellcat_fia",
 	"exile_chopper_huey_desert",
 	"exile_chopper_hummingbird_green",
 	"exile_chopper_hummingbird_civillian_blue",
 	"exile_chopper_hummingbird_civillian_red",
 	"exile_chopper_hummingbird_civillian_ion",
 	"exile_chopper_hummingbird_civillian_blueline",
 	"exile_chopper_hummingbird_civillian_digital",
 	"exile_chopper_hummingbird_civillian_elliptical",
 	"exile_chopper_hummingbird_civillian_furious",
 	"exile_chopper_hummingbird_civillian_graywatcher",
 	"exile_chopper_hummingbird_civillian_jeans",
 	"exile_chopper_hummingbird_civillian_light",
 	"exile_chopper_hummingbird_civillian_shadow",
 	"exile_chopper_hummingbird_civillian_sheriff",
 	"exile_chopper_hummingbird_civillian_speedy",
 	"exile_chopper_hummingbird_civillian_sunset",
 	"exile_chopper_hummingbird_civillian_vrana",
 	"exile_chopper_hummingbird_civillian_wasp",
 	"exile_chopper_hummingbird_civillian_wave",
 	"exile_bike_oldbike",
 	"exile_bike_mountainbike",
 	"exile_bike_quadbike_black",
 	"exile_bike_quadbike_blue",
 	"exile_bike_quadbike_red",
 	"exile_bike_quadbike_white",
 	"exile_bike_quadbike_nato",
 	"exile_bike_quadbike_csat",
 	"exile_bike_quadbike_fia",
 	"exile_bike_quadbike_guerilla01",
 	"exile_bike_quadbike_guerilla02",
 	"exile_car_kart_bluking",
 	"exile_car_kart_redstone",
 	"exile_car_kart_vrana",
 	"exile_car_kart_green",
 	"exile_car_kart_blue",
 	"exile_car_kart_orange",
 	"exile_car_kart_white",
 	"exile_car_kart_yellow",
 	"exile_car_kart_black",
 	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"cup_b_mtvr_usa",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_towtractor_white",
 	"cup_b_towingtractor_usmc",
 	"exile_car_octavius_white",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_hemmt",
 	"b_truck_01_transport_f",
 	"b_truck_01_covered_f",
 	"b_truck_01_mover_f",
 	"b_truck_01_box_f",
 	"b_truck_01_repair_f",
 	"b_truck_01_ammo_f",
 	"b_truck_01_fuel_f",
 	"b_t_truck_01_mover_f",
 	"b_t_truck_01_ammo_f",
 	"b_t_truck_01_box_f",
 	"b_t_truck_01_fuel_f",
 	"b_t_truck_01_medical_f",
 	"b_t_truck_01_repair_f",
 	"b_t_truck_01_transport_f",
 	"b_t_truck_01_covered_f",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"o_g_offroad_01_f",
 	"i_g_offroad_01_armed_f",
 	"c_van_01_fuel_white_v2_f",
 	"b_t_lsv_01_unarmed_sand_f",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"cup_b_hmmwv_unarmed_usmc",
 	"exile_car_tempest",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"o_truck_02_covered_f",
 	"o_truck_02_transport_f",
 	"i_truck_02_covered_f",
 	"i_truck_02_transport_f",
 	"c_truck_02_transport_f",
 	"o_truck_02_box_f",
 	"o_truck_02_medical_f",
 	"o_truck_02_ammo_f",
 	"o_truck_02_fuel_f",
 	"i_truck_02_box_f",
 	"i_truck_02_medical_f",
 	"i_truck_02_ammo_f",
 	"i_truck_02_fuel_f",
 	"c_truck_02_box_f",
 	"c_truck_02_fuel_f",
 	"c_idap_truck_02_f",
 	"c_idap_truck_02_transport_f",
 	"c_idap_truck_02_water_f",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"

];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["helicopter_base_f", 8],
 	["heli_attack_01_base_f", 2],
 	["heli_attack_02_base_f", 20],
 	["heli_light_02_base_f", 15],
 	["heli_transport_01_base_f", 15],
 	["heli_transport_02_base_f", 120],
 	["i_heli_light_03_base_f", 25],
 	["uav_01_base_f", 0],
 	["plane", 3],
 	["uav", 0],
 	["tank", 5],
 	["car", 6],
 	["motorcycle", 2],
 	["truck_f", 100],
 	["bus", 30],
 	["kart_01_base_f", 2],
 	["mrap_01_base_f", 12],
 	["mrap_02_base_f", 12],
 	["mrap_03_base_f", 12],
 	["offroad_01_base_f", 10],
 	["offroad_01_armed_base_f", 4],
 	["quadbike_01_base_f", 3],
 	["quadbike_base_f", 3],
 	["truck_02_base_f", 120],
 	["o_truck_03_ammo_f", 140],
 	["o_truck_03_device_f", 5],
 	["o_truck_03_fuel_f", 5],
 	["van_01_base_f", 5],
 	["c_van_01_box_f", 40],
 	["c_van_01_transport_f", 25],
 	["i_g_van_01_transport_f", 25],
 	["wheeled_apc_f", 10],
 	["ship_f", 5],
 	["boat_civil_01_base_f", 10],
 	["boat_armed_01_base_f", 15],
 	["b_supplycrate_f", 9],
 	["c_supplycrate_f", 9],
 	["box_east_ammoveh_f", 14],
 	["ig_supplycrate_f", 9],
 	["box_ind_ammoveh_f", 14],
 	["box_nato_ammoveh_f", 14],
 	["cargo_base_f", 170],
 	["land_cargobox_v1_f", 14],
 	["cargo10_base_f", 40],
 	["metalcase_01_base_f", 4],
 	["plasticcase_01_base_f", 4],
 	["cargonet_01_base_f", 14],
 	["b_slingload_01_cargo_f", 110],
 	["b_slingload_01_ammo_f", 90],
 	["b_heli_transport_03_base_f", 70],
 	["o_heli_transport_04_ammo_f", 40],
 	["o_heli_transport_04_box_f", 40],
 	["heli_transport_04_base_f", 40],
 	["o_heli_transport_04_bench_f", 5],
 	["o_heli_transport_04_f", 5],
 	["o_heli_transport_04_fuel_f", 5],
 	["ah1_base", 5],
 	["ah64_base_ep1", 10],
 	["ah6_base_ep1", 20],
 	["aw159_lynx_baf", 40],
 	["baf_merlin_hc3_d", 100],
 	["ch47_base_ep1", 130],
 	["ka60_base_pmc", 60],
 	["kamov_base", 10],
 	["mi17_base", 80],
 	["mi24_base", 50],
 	["uh1h_base", 40],
 	["uh1_base", 40],
 	["uh60_base", 60],
 	["an2_base_ep1", 50],
 	["c130j", 250],
 	["dc3", 90],
 	["mv22", 60],
 	["atv_base_ep1", 3],
 	["armoredsuv_base_pmc", 15],
 	["baf_jackal2_base_d", 18],
 	["datsun_pk1", 10],
 	["dingo_base_acr", 25],
 	["hilux_pk1", 10],
 	["hmmwv_base", 18],
 	["hmmwv_avenger", 5],
 	["ikarus", 60],
 	["landrover_base", 15],
 	["offroad_dshkm_base", 10],
 	["pickup_pk_base", 10],
 	["s1203_tk_civ_ep1", 20],
 	["suv_base_ep1", 12],
 	["kamaz_base", 100],
 	["mtvr", 80],
 	["t810_turrets_base_acr", 80],
 	["truck_base_h", 50],
 	["ural_base_withturret", 10],
 	["ural_base", 100],
 	["v3s_base", 90],
 	["uaz_base", 15],
 	["brdm2_base", 15],
 	["btr40_mg_base_ep1", 12],
 	["btr90_base", 18],
 	["gaz_vodnik_hmg", 18],
 	["lav25_base", 18],
 	["strykerbase_ep1", 18],
 	["hilux1_civil_1_open", 12],
 	["baf_fv510_d", 8],
 	["m113_base", 10],
 	["m2a2_ep1", 8],
 	["aav", 8],
 	["land_misc_cargo1ao", 110],
 	["land_misc_cargo1a_ep1", 110],
 	["land_misc_cargo1ao_ep1", 110],
 	["land_misc_cargo1b", 110],
 	["land_misc_cargo1b_ep1", 110],
 	["land_misc_cargo1bo", 110],
 	["land_misc_cargo1c", 110],
 	["land_misc_cargo1c_ep1", 110],
 	["land_misc_cargo1d", 110],
 	["land_misc_cargo1d_ep1", 110],
 	["land_misc_cargo1e", 110],
 	["land_misc_cargo1e_ep1", 110],
 	["land_misc_cargo1f", 110],
 	["land_misc_cargo1g", 110],
 	["land_misc_cargomarket1a_ep1", 110],
 	["base_warfarebcontructionsite", 110],
 	["fortress2", 20],
 	["warfarebcamp", 30],
 	["misc_cargo_cont_small", 65],
 	["misc_cargo_cont_small2", 50],
 	["cup_b_aw159_hellfire_gb", 50],
 	["cup_b_aw159_cannon_gb", 50],
 	["cup_b_aw159_hellfire_rn_grey", 50],
 	["cup_b_aw159_cannon_rn_grey", 50],
 	["cup_b_aw159_hellfire_rn_blackcat", 50],
 	["cup_b_aw159_cannon_rn_blackcat", 50],
 	["cup_b_mh60s_usmc", 50],
 	["cup_b_mi24_d_cdf", 75],
 	["cup_b_mi35_cz", 75],
 	["cup_b_mi35_cz_des", 75],
 	["cup_b_mi35_cz_ram", 75],
 	["cup_b_mi35_cz_tiger", 75],
 	["cup_b_mi35_cz_dark", 75],
 	["cup_b_merlin_hc3_armed_gb", 100],
 	["cup_b_merlin_hc3a_armed_gb", 100],
 	["exile_chopper_huey_armed_green", 25],
 	["exile_chopper_huey_armed_desert", 25],
 	["cup_b_uh60m_ffv_us", 50],
 	["cup_b_uh60l_ffv_us", 50],
 	["cup_b_ah6j_escort_usa", 15],
 	["cup_b_ah6j_at_usa", 15],
 	["cup_b_ah6j_mp_usa", 15],
 	["cup_b_ah6j_escort19_usa", 15],
 	["b_heli_transport_01_f", 50],
 	["b_heli_transport_01_camo_f", 50],
 	["b_ctrg_heli_transport_01_sand_f", 50],
 	["b_ctrg_heli_transport_01_tropic_f", 50],
 	["cup_i_mi24_mk4_aaf", 75],
 	["cup_o_mi24_mk4_csat_t", 75],
 	["cup_i_mi24_mk4_ion", 75],
 	["cup_i_mi24_mk4_un", 75],
 	["o_heli_attack_02_f", 75],
 	["o_heli_attack_02_black_f", 75],
 	["o_heli_attack_02_dynamicloadout_f", 75],
 	["b_t_lsv_01_armed_f", 25],
 	["b_t_lsv_01_armed_ctrg_f", 25],
 	["b_lsv_01_armed_f", 25],
 	["b_lsv_01_armed_olive_f", 25],
 	["b_lsv_01_armed_sand_f", 25],
 	["b_lsv_01_armed_black_f", 25],
 	["b_t_lsv_01_armed_olive_f", 25],
 	["b_t_lsv_01_armed_sand_f", 25],
 	["b_t_lsv_01_armed_black_f", 25],
 	["o_t_lsv_02_armed_viper_f", 25],
 	["o_t_lsv_02_armed_f", 25],
 	["o_lsv_02_armed_viper_f", 25],
 	["o_lsv_02_armed_f", 25],
 	["o_t_lsv_02_armed_black_f", 25],
 	["o_t_lsv_02_armed_ghex_f", 25],
 	["o_t_lsv_02_armed_arid_f", 25],
 	["o_lsv_02_armed_black_f", 25],
 	["o_lsv_02_armed_ghex_f", 25],
 	["o_lsv_02_armed_arid_f", 25],
 	["exile_car_offroad_armed_guerilla01", 25],
 	["exile_car_offroad_armed_guerilla02", 25],
 	["exile_car_offroad_armed_guerilla03", 25],
 	["exile_car_offroad_armed_guerilla04", 25],
 	["exile_car_offroad_armed_guerilla05", 25],
 	["exile_car_offroad_armed_guerilla06", 25],
 	["exile_car_offroad_armed_guerilla07", 25],
 	["exile_car_offroad_armed_guerilla08", 25],
 	["exile_car_offroad_armed_guerilla09", 25],
 	["exile_car_offroad_armed_guerilla10", 25],
 	["exile_car_offroad_armed_guerilla11", 25],
 	["exile_car_offroad_armed_guerilla12", 25],
 	["i_g_offroad_01_f", 25],
 	["exile_car_suv_armed_black", 25],
 	["exile_car_btr40_mg_green", 25],
 	["exile_car_btr40_mg_camo", 25],
 	["exile_car_hmmwv_m134_green", 25],
 	["exile_car_hmmwv_m134_desert", 25],
 	["exile_car_hmmwv_m2_green", 25],
 	["exile_car_hmmwv_m2_desert", 25],
 	["cup_b_hmmwv_m2_usmc", 25],
 	["cup_b_hmmwv_m2_usa", 25],
 	["cup_b_hmmwv_m2_gpk_usa", 25],
 	["cup_b_hmmwv_m2_gpk_acr", 25],
 	["cup_b_hmmwv_dshkm_gpk_acr", 25],
 	["cup_b_hmmwv_crows_m2_usa", 25],
 	["cup_b_hmmwv_sov_usa", 25],
 	["cup_b_hmmwv_mk19_usmc", 25],
 	["cup_b_hmmwv_mk19_usa", 25],
 	["cup_b_hmmwv_ags_gpk_acr", 25],
 	["cup_b_hmmwv_crows_mk19_usa", 25],
 	["cup_b_hmmwv_tow_usmc", 25],
 	["cup_b_hmmwv_tow_usa", 25],
 	["cup_b_hmmwv_m1114_usmc", 25],
 	["cup_b_lr_mg_gb_w", 25],
 	["cup_b_lr_special_cz_w", 25],
 	["cup_b_lr_special_des_cz_d", 25],
 	["cup_b_lr_special_gmg_gb_w", 25],
 	["cup_b_lr_special_gmg_gb_d", 25],
 	["cup_b_lr_special_m2_gb_w", 25],
 	["cup_b_lr_special_m2_gb_d", 25],
 	["cup_b_baf_coyote_l2a1_d", 25],
 	["cup_b_baf_coyote_l2a1_w", 25],
 	["cup_b_baf_coyote_gmg_d", 25],
 	["cup_b_baf_coyote_gmg_w", 25],
 	["cup_b_jackal2_l2a1_gb_d", 25],
 	["cup_b_jackal2_l2a1_gb_w", 25],
 	["cup_b_jackal2_gmg_gb_d", 25],
 	["cup_b_jackal2_gmg_gb_w", 25],
 	["cup_b_uaz_mg_cdf", 25],
 	["cup_b_uaz_mg_acr", 25],
 	["cup_b_uaz_ags30_cdf", 25],
 	["cup_b_uaz_ags30_acr", 25],
 	["cup_b_uaz_spg9_cdf", 25],
 	["cup_b_uaz_spg9_acr", 25],
 	["cup_b_uaz_metis_cdf", 25],
 	["cup_b_uaz_metis_acr", 25],
 	["cup_i_ural_zu23_napa", 15],
 	["cup_b_zodiac_usmc", 15],
 	["cup_b_rhib_usmc", 25],
 	["cup_b_rhib2turret_usmc", 25],
 	["b_g_boat_transport_02_f", 25],
 	["o_g_boat_transport_02_f", 25],
 	["i_g_boat_transport_02_f", 25],
 	["i_c_boat_transport_02_f", 25],
 	["c_boat_transport_02_f", 25],
 	["exile_boat_rhib", 25],
 	["exile_boat_sdv_csat", 15],
 	["exile_boat_sdv_digital", 15],
 	["exile_boat_sdv_grey", 15],
 	["exile_boat_rubberduck_csat", 15],
 	["exile_boat_rubberduck_digital", 15],
 	["exile_boat_rubberduck_orange", 15],
 	["exile_boat_rubberduck_blue", 15],
 	["exile_boat_rubberduck_black", 15],
 	["exile_boat_motorboat_police", 25],
 	["exile_boat_motorboat_orange", 25],
 	["exile_boat_motorboat_white", 25],
 	["cup_c_fishing_boat_chernarus", 100],
 	["o_boat_armed_01_hmg_f", 25],
 	["i_boat_armed_01_minigun_f", 25],
 	["b_t_boat_armed_01_minigun_f", 25],
 	["b_boat_armed_01_minigun_f", 25],
 	["o_t_boat_armed_01_hmg_f", 25],
 	["cup_b_uh1d_ger_ksk", 25],
 	["cup_b_uh1d_ger_ksk_des", 25],
 	["cup_b_uh60m_us", 50],
 	["cup_b_uh60l_us", 50],
 	["cup_b_uh60m_unarmed_us", 50],
 	["cup_b_uh60l_unarmed_us", 50],
 	["cup_b_uh60m_unarmed_ffv_us", 50],
 	["cup_b_uh60l_unarmed_ffv_us", 50],
 	["cup_b_mh6j_usa", 15],
 	["cup_b_aw159_unarmed_gb", 50],
 	["cup_b_wildcat_unarmed_rn_blackcat", 50],
 	["cup_b_mh60s_ffv_usmc", 50],
 	["cup_b_c130j_usmc", 200],
 	["cup_b_c130j_cargo_usmc", 200],
 	["cup_b_c130j_gb", 200],
 	["cup_b_c130j_cargo_gb", 200],
 	["cup_b_ch47f_usa", 100],
 	["cup_b_ch47f_viv_usa", 100],
 	["cup_b_ch47f_gb", 100],
 	["cup_b_ch47f_viv_gb", 100],
 	["cup_b_mi6a_cdf", 150],
 	["cup_b_mi6t_cdf", 150],
 	["cup_b_mi17_cdf", 75],
 	["cup_b_mi17_viv_cdf", 75],
 	["cup_b_mi171sh_acr", 75],
 	["cup_b_mi171sh_unarmed_acr", 75],
 	["cup_b_mv22_usmc", 175],
 	["cup_b_mv22_viv_usmc", 175],
 	["cup_b_mv22_usmc_rampgun", 175],
 	["cup_b_ch53e_usmc", 100],
 	["cup_b_ch53e_viv_usmc", 100],
 	["cup_b_ch53e_ger", 100],
 	["cup_b_ch53e_viv_ger", 100],
 	["cup_b_c47_usa", 100],
 	["cup_b_ac47_spooky_usa", 100],
 	["cup_b_merlin_hc3_gb", 100],
 	["cup_b_merlin_hc3_viv_gb", 100],
 	["cup_b_merlin_hc3a_gb", 100],
 	["cup_b_merlin_hc4_gb", 100],
 	["cup_b_sa330_puma_hc1_baf", 75],
 	["cup_b_sa330_puma_hc2_baf", 75],
 	["cup_b_uh1y_gunship_usmc", 50],
 	["cup_b_uh1y_una_usmc", 50],
 	["cup_b_bmp2_cdf", 25],
 	["cup_b_bmp_hq_cdf", 25],
 	["cup_b_bmp2_cz", 25],
 	["cup_b_bmp2_cz_des", 25],
 	["cup_b_bmp_hq_cz", 25],
 	["cup_b_bmp_hq_cz_des", 25],
 	["cup_b_brdm2_cdf", 50],
 	["cup_b_brdm2_atgm_cdf", 50],
 	["cup_b_brdm2_hq_cdf", 50],
 	["cup_b_brdm2_cz", 50],
 	["cup_b_brdm2_cz_des", 50],
 	["cup_b_brdm2_hq_cz", 50],
 	["cup_b_brdm2_hq_des", 50],
 	["cup_b_t72_cdf", 15],
 	["cup_b_t72_cz", 15],
 	["cup_b_btr60_cdf", 50],
 	["cup_b_lav25_usmc", 50],
 	["cup_b_lav25m240_usmc", 50],
 	["cup_b_lav25_hq_usmc", 50],
 	["cup_b_m1126_icv_m2_desert", 50],
 	["cup_b_m1126_icv_m2_desert_slat", 50],
 	["cup_b_m1126_icv_m2_woodland", 50],
 	["cup_b_m1126_icv_m2_woodland_slat", 50],
 	["cup_b_m1126_icv_mk19_desert", 50],
 	["cup_b_m1126_icv_mk19_desert_slat", 50],
 	["cup_b_m1126_icv_mk19_woodland", 50],
 	["cup_b_m1126_icv_mk19_woodland_slat", 50],
 	["cup_b_m1130_cv_m2_desert", 50],
 	["cup_b_m1130_cv_m2_desert_slat", 50],
 	["cup_b_m1130_cv_m2_woodland", 50],
 	["cup_b_m1130_cv_m2_woodland_slat", 50],
 	["cup_b_m1129_mc_mk19_desert", 50],
 	["cup_b_m1129_mc_mk19_desert_slat", 50],
 	["cup_b_m1129_mc_mk19_woodland", 50],
 	["cup_b_m1129_mc_mk19_woodland_slat", 50],
 	["cup_b_m1135_atgmv_desert", 50],
 	["cup_b_m1135_atgmv_desert_slat", 50],
 	["cup_b_m1135_atgmv_woodland", 50],
 	["cup_b_m1135_atgmv_woodland_slat", 50],
 	["cup_b_m1128_mgs_desert", 50],
 	["cup_b_m1128_mgs_desert_slat", 50],
 	["cup_b_m1128_mgs_woodland", 50],
 	["cup_b_m1128_mgs_woodland_slat", 50],
 	["cup_b_aav_usmc", 50],
 	["cup_b_fv432_bulldog_gb_d", 50],
 	["cup_b_fv432_bulldog_gb_w", 50],
 	["cup_b_fv432_bulldog_gb_d_rws", 50],
 	["cup_b_fv432_bulldog_gb_w_rws", 50],
 	["cup_b_fv510_gb_d_slat", 50],
 	["cup_b_fv510_gb_w_slat", 50],
 	["cup_b_fv510_gb_d", 50],
 	["cup_b_fv510_gb_w", 50],
 	["cup_b_m113_usa", 50],
 	["cup_b_m163_usa", 50],
 	["cup_b_mcv80_gb_d_slat", 50],
 	["cup_b_mcv80_gb_w_slat", 50],
 	["cup_b_mcv80_gb_d", 50],
 	["cup_b_mcv80_gb_w", 50],
 	["cup_b_m2bradley_usa_d", 50],
 	["cup_b_m2bradley_usa_w", 50],
 	["cup_b_m6linebacker_usa_d", 50],
 	["cup_b_m6linebacker_usa_w", 50],
 	["cup_b_m2a3bradley_usa_d", 50],
 	["cup_b_m2a3bradley_usa_w", 50],
 	["cup_b_m7bradley_usa_d", 50],
 	["cup_b_m270_he_usmc", 15],
 	["cup_b_m270_dpicm_usmc", 15],
 	["cup_b_m270_he_usa", 15],
 	["cup_b_m270_dpicm_usa", 15],
 	["cup_b_zsu23_cdf", 25],
 	["cup_b_ah6x_usa", 15],
 	["cup_b_dingo_cz_wdl", 50],
 	["cup_b_dingo_cz_des", 50],
 	["cup_b_dingo_gl_cz_wdl", 50],
 	["cup_b_dingo_gl_cz_des", 50],
 	["cup_b_dingo_ger_wdl", 50],
 	["cup_b_dingo_ger_des", 50],
 	["cup_b_dingo_gl_ger_wdl", 50],
 	["cup_b_dingo_gl_ger_des", 50],
 	["cup_b_lr_transport_cz_w", 25],
 	["cup_b_lr_transport_cz_d", 25],
 	["cup_b_lr_mg_cz_w", 25],
 	["cup_b_lr_transport_gb_w", 25],
 	["cup_b_lr_transport_gb_d", 25],
 	["cup_b_mastiff_hmg_gb_d", 75],
 	["cup_b_mastiff_hmg_gb_w", 75],
 	["cup_b_mastiff_gmg_gb_d", 75],
 	["cup_b_mastiff_gmg_gb_w", 75],
 	["cup_b_mastiff_lmg_gb_d", 75],
 	["cup_b_mastiff_lmg_gb_w", 75],
 	["cup_b_mtvr_usa", 75],
 	["cup_b_mtvr_usmc", 75],
 	["cup_b_ridgback_hmg_gb_d", 75],
 	["cup_b_ridgback_hmg_gb_w", 75],
 	["cup_b_ridgback_gmg_gb_d", 75],
 	["cup_b_ridgback_gmg_gb_w", 75],
 	["cup_b_ridgback_lmg_gb_d", 75],
 	["cup_b_ridgback_lmg_gb_w", 75],
 	["cup_b_uaz_unarmed_cdf", 25],
 	["cup_b_uaz_open_cdf", 25],
 	["cup_b_uaz_unarmed_acr", 25],
 	["cup_b_uaz_open_acr", 25],
 	["cup_b_ural_cdf", 75],
 	["cup_b_ural_open_cdf", 75],
 	["cup_b_ural_zu23_cdf", 15],
 	["cup_b_wolfhound_hmg_gb_d", 75],
 	["cup_b_wolfhound_hmg_gb_w", 75],
 	["cup_b_wolfhound_gmg_gb_d", 75],
 	["cup_b_wolfhound_gmg_gb_w", 75],
 	["cup_b_wolfhound_lmg_gb_d", 75],
 	["cup_b_wolfhound_lmg_gb_w", 75],
 	["cup_b_rg31_m2_usmc", 25],
 	["cup_b_rg31_m2_od_usmc", 25],
 	["cup_b_rg31_m2_gc_usmc", 25],
 	["cup_b_rg31_mk19_usmc", 25],
 	["cup_b_rg31_mk19_od_usmc", 25],
 	["cup_b_rg31e_m2_usmc", 25],
 	["cup_b_hmmwv_unarmed_usa", 25],
 	["cup_b_hmmwv_transport_usa", 25],
 	["cup_b_hmmwv_terminal_usa", 50],
 	["cup_b_bmp2_amb_cdf", 50],
 	["cup_b_bmp2_amb_cz", 50],
 	["cup_b_bmp2_amb_cz_des", 50],
 	["cup_b_lr_ambulance_cz_w", 50],
 	["cup_b_lr_ambulance_cz_d", 50],
 	["cup_b_lr_ambulance_gb_w", 50],
 	["cup_b_lr_ambulance_gb_d", 50],
 	["cup_b_uh60l_unarmed_ffv_mev_us", 75],
 	["cup_b_mtvr_ammo_usa", 75],
 	["cup_b_mtvr_repair_usa", 75],
 	["cup_b_mtvr_ammo_usmc", 75],
 	["cup_b_mtvr_repair_usmc", 75],
 	["cup_b_ural_repair_cdf", 75],
 	["cup_b_ural_reammo_cdf", 75],
 	["cup_b_m1133_mev_desert", 50],
 	["cup_b_m1133_mev_desert_slat", 50],
 	["cup_b_m1133_mev_woodland", 50],
 	["cup_b_m1133_mev_woodland_slat", 50],
 	["cup_b_mi24_d_mev_cdf", 75],
 	["cup_b_mi17_medevac_cdf", 100],
 	["cup_b_m113_med_usa", 50],
 	["cup_b_hmmwv_ambulance_usmc", 50],
 	["cup_b_hmmwv_ambulance_usa", 50],
 	["cup_b_hmmwv_ambulance_acr", 50],
 	["cup_b_uh1y_mev_usmc", 50],
 	["exile_car_brdm2_hq", 50],
 	["exile_car_ifrit", 50],
 	["exile_car_hunter", 50],
 	["exile_car_strider", 50],
 	["o_t_mrap_02_hmg_ghex_f", 50],
 	["o_t_mrap_02_gmg_ghex_f", 50],
 	["b_mrap_01_gmg_f", 50],
 	["b_mrap_01_hmg_f", 50],
 	["b_t_mrap_01_gmg_f", 50],
 	["b_t_mrap_01_hmg_f", 50],
 	["i_mrap_03_hmg_f", 50],
 	["i_mrap_03_gmg_f", 50],
 	["o_apc_tracked_02_aa_f", 15],
 	["o_apc_tracked_02_cannon_f", 50],
 	["i_apc_wheeled_03_cannon_f", 50],
 	["i_apc_tracked_03_cannon_f", 50],
 	["b_apc_tracked_01_rcws_f", 50],
 	["b_apc_tracked_01_crv_f", 50],
 	["b_apc_tracked_01_aa_f", 25],
 	["exile_plane_cessna", 25],
 	["exile_plane_an2_green", 50],
 	["exile_plane_an2_white", 50],
 	["exile_plane_an2_stripe", 50],
 	["exile_plane_ceasar", 25],
 	["exile_plane_blackfishinfantry", 200],
 	["exile_plane_blackfishvehicle", 200],
 	["exile_chopper_huey_green", 25],
 	["exile_chopper_hellcat_green", 25],
 	["exile_chopper_hellcat_fia", 25],
 	["exile_chopper_huey_desert", 25],
 	["exile_chopper_hummingbird_green", 15],
 	["exile_chopper_hummingbird_civillian_blue", 15],
 	["exile_chopper_hummingbird_civillian_red", 15],
 	["exile_chopper_hummingbird_civillian_ion", 15],
 	["exile_chopper_hummingbird_civillian_blueline", 15],
 	["exile_chopper_hummingbird_civillian_digital", 15],
 	["exile_chopper_hummingbird_civillian_elliptical", 15],
 	["exile_chopper_hummingbird_civillian_furious", 15],
 	["exile_chopper_hummingbird_civillian_graywatcher", 15],
 	["exile_chopper_hummingbird_civillian_jeans", 15],
 	["exile_chopper_hummingbird_civillian_light", 15],
 	["exile_chopper_hummingbird_civillian_shadow", 15],
 	["exile_chopper_hummingbird_civillian_sheriff", 15],
 	["exile_chopper_hummingbird_civillian_speedy", 15],
 	["exile_chopper_hummingbird_civillian_sunset", 15],
 	["exile_chopper_hummingbird_civillian_vrana", 15],
 	["exile_chopper_hummingbird_civillian_wasp", 15],
 	["exile_chopper_hummingbird_civillian_wave", 15],
 	["exile_chopper_huron_black", 125],
 	["exile_chopper_huron_green", 125],
 	["exile_chopper_mohawk_fia", 100],
 	["exile_chopper_orca_csat", 50],
 	["exile_chopper_orca_black", 50],
 	["exile_chopper_orca_blackcustom", 50],
 	["exile_chopper_taru_covered_csat", 50],
 	["exile_chopper_taru_covered_black", 50],
 	["cup_b_uh60m_unarmed_ffv_mev_us", 50],
 	["exile_bike_quadbike_black", 15],
 	["exile_bike_quadbike_blue", 15],
 	["exile_bike_quadbike_red", 15],
 	["exile_bike_quadbike_white", 25],
 	["exile_bike_quadbike_nato", 15],
 	["exile_bike_quadbike_csat", 15],
 	["exile_bike_quadbike_fia", 15],
 	["exile_bike_quadbike_guerilla01", 15],
 	["exile_bike_quadbike_guerilla02", 15],
 	["exile_car_hatchback_beige", 15],
 	["exile_car_hatchback_green", 15],
 	["exile_car_hatchback_blue", 15],
 	["exile_car_hatchback_bluecustom", 15],
 	["exile_car_hatchback_beigecustom", 15],
 	["exile_car_hatchback_yellow", 15],
 	["exile_car_hatchback_grey", 15],
 	["exile_car_hatchback_black", 15],
 	["exile_car_hatchback_dark", 15],
 	["exile_car_hatchback_rusty1", 15],
 	["exile_car_hatchback_rusty2", 15],
 	["exile_car_hatchback_rusty3", 15],
 	["exile_car_golf_red", 15],
 	["exile_car_golf_black", 15],
 	["exile_car_ikarus_blue", 100],
 	["exile_car_ikarus_red", 100],
 	["exile_car_ikarus_party", 100],
 	["exile_car_ural_open_blue", 75],
 	["exile_car_ural_open_yellow", 75],
 	["exile_car_ural_open_worker", 75],
 	["exile_car_ural_open_military", 75],
 	["exile_car_ural_covered_blue", 75],
 	["exile_car_ural_covered_yellow", 75],
 	["exile_car_ural_covered_worker", 75],
 	["exile_car_ural_covered_military", 75],
 	["exile_car_v3s_open", 75],
 	["exile_car_v3s_covered", 75],
 	["exile_car_suvxl_black", 25],
 	["exile_car_octavius_white", 15],
 	["exile_car_octavius_black", 15],
 	["exile_car_uaz_green", 25],
 	["exile_car_uaz_open_green", 25],
 	["exile_car_landrover_red", 25],
 	["exile_car_landrover_urban", 25],
 	["exile_car_landrover_green", 25],
 	["exile_car_landrover_sand", 25],
 	["exile_car_landrover_desert", 25],
 	["exile_car_landrover_ambulance_green", 50],
 	["exile_car_landrover_ambulance_desert", 50],
 	["exile_car_landrover_ambulance_sand", 50],
 	["exile_car_lada_green", 15],
 	["exile_car_lada_taxi", 15],
 	["exile_car_lada_red", 15],
 	["exile_car_lada_white", 15],
 	["exile_car_lada_hipster", 15],
 	["exile_car_volha_blue", 15],
 	["exile_car_volha_white", 15],
 	["exile_car_volha_black", 15],
 	["exile_car_hatchback_sport_red", 15],
 	["exile_car_hatchback_sport_blue", 15],
 	["exile_car_hatchback_sport_orange", 15],
 	["exile_car_hatchback_sport_white", 15],
 	["exile_car_hatchback_sport_beige", 15],
 	["exile_car_hatchback_sport_green", 15],
 	["exile_car_hemmt", 100],
 	["b_truck_01_transport_f", 100],
 	["b_truck_01_covered_f", 100],
 	["b_truck_01_box_f", 100],
 	["b_truck_01_repair_f", 100],
 	["b_truck_01_ammo_f", 100],
 	["b_t_truck_01_ammo_f", 100],
 	["b_t_truck_01_box_f", 100],
 	["b_t_truck_01_medical_f", 100],
 	["b_t_truck_01_repair_f", 100],
 	["b_t_truck_01_transport_f", 100],
 	["b_t_truck_01_covered_f", 100],
 	["exile_car_offroad_beige", 25],
 	["exile_car_offroad_red", 25],
 	["exile_car_offroad_white", 25],
 	["exile_car_offroad_blue", 25],
 	["exile_car_offroad_darkred", 25],
 	["exile_car_offroad_bluecustom", 25],
 	["exile_car_offroad_guerilla01", 25],
 	["exile_car_offroad_guerilla02", 25],
 	["exile_car_offroad_guerilla03", 25],
 	["exile_car_offroad_guerilla04", 25],
 	["exile_car_offroad_guerilla05", 25],
 	["exile_car_offroad_guerilla06", 25],
 	["exile_car_offroad_guerilla07", 25],
 	["exile_car_offroad_guerilla08", 25],
 	["exile_car_offroad_guerilla09", 25],
 	["exile_car_offroad_guerilla10", 25],
 	["exile_car_offroad_guerilla11", 25],
 	["exile_car_offroad_guerilla12", 25],
 	["exile_car_offroad_rusty1", 25],
 	["exile_car_offroad_rusty2", 25],
 	["exile_car_offroad_rusty3", 25],
 	["exile_car_offroad_repair_civillian", 25],
 	["exile_car_offroad_repair_red", 25],
 	["exile_car_offroad_repair_beige", 25],
 	["exile_car_offroad_repair_white", 25],
 	["exile_car_offroad_repair_blue", 25],
 	["exile_car_offroad_repair_darkred", 25],
 	["exile_car_offroad_repair_bluecustom", 25],
 	["exile_car_offroad_repair_guerilla01", 25],
 	["exile_car_offroad_repair_guerilla02", 25],
 	["exile_car_offroad_repair_guerilla03", 25],
 	["exile_car_offroad_repair_guerilla04", 25],
 	["exile_car_offroad_repair_guerilla05", 25],
 	["exile_car_offroad_repair_guerilla06", 25],
 	["exile_car_offroad_repair_guerilla07", 25],
 	["exile_car_offroad_repair_guerilla08", 25],
 	["exile_car_offroad_repair_guerilla09", 25],
 	["exile_car_offroad_repair_guerilla10", 25],
 	["exile_car_offroad_repair_guerilla11", 25],
 	["exile_car_offroad_repair_guerilla12", 25],
 	["o_g_offroad_01_f", 25],
 	["i_g_offroad_01_armed_f", 25],
 	["b_t_lsv_01_unarmed_sand_f", 25],
 	["exile_car_suv_red", 15],
 	["exile_car_suv_black", 15],
 	["exile_car_suv_grey", 15],
 	["exile_car_suv_orange", 15],
 	["exile_car_btr40_green", 25],
 	["exile_car_btr40_camo", 25],
 	["exile_car_hmmwv_mev_green", 25],
 	["exile_car_hmmwv_mev_desert", 25],
 	["exile_car_hmmwv_una_green", 25],
 	["exile_car_hmmwv_una_desert", 25],
 	["cup_b_hmmwv_unarmed_usmc", 25],
 	["exile_car_tempest", 75],
 	["exile_car_van_black", 50],
 	["exile_car_van_white", 50],
 	["exile_car_van_red", 50],
 	["exile_car_van_guerilla01", 50],
 	["exile_car_van_guerilla02", 50],
 	["exile_car_van_guerilla03", 50],
 	["exile_car_van_guerilla04", 50],
 	["exile_car_van_guerilla05", 50],
 	["exile_car_van_guerilla06", 50],
 	["exile_car_van_guerilla07", 50],
 	["exile_car_van_guerilla08", 50],
 	["exile_car_van_box_black", 50],
 	["exile_car_van_box_white", 50],
 	["exile_car_van_box_red", 50],
 	["exile_car_van_box_guerilla01", 50],
 	["exile_car_van_box_guerilla02", 50],
 	["exile_car_van_box_guerilla03", 50],
 	["exile_car_van_box_guerilla04", 50],
 	["exile_car_van_box_guerilla05", 50],
 	["exile_car_van_box_guerilla06", 50],
 	["exile_car_van_box_guerilla07", 50],
 	["exile_car_van_box_guerilla08", 50],
 	["exile_car_zamak", 75],
 	["o_truck_02_covered_f", 75],
 	["o_truck_02_transport_f", 75],
 	["i_truck_02_covered_f", 75],
 	["i_truck_02_transport_f", 75],
 	["c_truck_02_transport_f", 75],
 	["o_truck_02_box_f", 75],
 	["o_truck_02_medical_f", 75],
 	["o_truck_02_ammo_f", 75],
 	["i_truck_02_box_f", 75],
 	["i_truck_02_medical_f", 75],
 	["i_truck_02_ammo_f", 75],
 	["c_truck_02_box_f", 75],
 	["c_idap_truck_02_f", 75],
 	["c_idap_truck_02_transport_f", 75],
 	["exile_car_prowlerunarmed", 25],
 	["exile_car_qilinunarmed", 25],
 	["exile_car_mb4wd", 15],
 	["exile_car_mb4wdopen", 15]
];
LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	["uav_01_base_f", 3],
 	["uav_02_base_f", 100],
 	["kart_01_base_f", 40],
 	["quadbike_01_base_f", 40],
 	["ugv_01_base_f", 100],
 	["staticweapon", 5],
 	["staticmortar", 6],
 	["land_camping_light_f", 1],
 	["roadcone_l_f", 1],
 	["roadbarrier_small_f", 1],
 	["rubber_duck_base_f", 40],
 	["camping_base_f", 1],
 	["flagsmall_f", 1],
 	["hbarrier_base_f", 3],
 	["land_hbarriertower_f", 8],
 	["land_hbarrierwall6_f", 4],
 	["land_hbarrierwall_corridor_f", 4],
 	["land_hbarrier_1_f", 1],
 	["land_hbarrier_3_f", 2],
 	["helper_base_f", 1],
 	["helih", 1],
 	["land_portablelight_single_f", 1],
 	["land_metalbarrel_empty_f", 2],
 	["land_campfire_f", 1],
 	["land_fireplace_f", 1],
 	["land_obstacle_bridge_f", 2],
 	["land_razorwire_f", 2],
 	["land_sign_mines_f", 1],
 	["land_pallet_milboxes_f", 5],
 	["land_paperbox_closed_f", 5],
 	["land_paperbox_open_empty_f", 5],
 	["land_paperbox_open_full_f", 5],
 	["land_bargate_f", 2],
 	["land_cncbarriermedium4_f", 6],
 	["land_cncbarriermedium_f", 2],
 	["land_cncbarrier_f", 2],
 	["land_cncbarrier_stripes_f", 2],
 	["land_cncwall1_f", 2],
 	["land_cncwall4_f", 6],
 	["land_mil_concretewall_f", 2],
 	["land_shoot_house_wall_f", 2],
 	["sign_f", 2],
 	["signad_sponsors_f", 1],
 	["shelter_base_f", 2],
 	["land_plasticbarrier_01_f", 2],
 	["land_plasticbarrier_02_f", 2],
 	["bagbunker_base_f", 15],
 	["land_bagbunker_small_f", 6],
 	["bagfence_base_f", 2],
 	["flagcarriercore", 2],
 	["reammobox_f", 4],
 	["b_supplycrate_f", 10],
 	["c_supplycrate_f", 10],
 	["box_east_ammoord_f", 2],
 	["box_east_ammoveh_f", 15],
 	["box_east_ammo_f", 2],
 	["box_east_grenades_f", 2],
 	["box_east_support_f", 2],
 	["box_east_wpslaunch_f", 2],
 	["box_east_wps_f", 3],
 	["ig_supplycrate_f", 10],
 	["box_ind_ammoord_f", 2],
 	["box_ind_ammoveh_f", 15],
 	["box_ind_ammo_f", 2],
 	["box_ind_grenades_f", 2],
 	["box_ind_support_f", 2],
 	["box_ind_wpslaunch_f", 2],
 	["box_ind_wps_f", 3],
 	["land_box_ammoold_f", 2],
 	["box_nato_ammoveh_f", 15],
 	["box_nato_ammo_f", 2],
 	["box_nato_grenades_f", 2],
 	["box_nato_support_f", 2],
 	["box_nato_wpslaunch_f", 2],
 	["targetbase", 3],
 	["land_pierladder_f", 3],
 	["metal_pole_f", 1],
 	["arrowmarker_r_f", 1],
 	["land_pallet_f", 2],
 	["land_pallets_stack_f", 4],
 	["land_chairplastic_f", 1],
 	["land_chairwood_f", 1],
 	["items_base_f", 1],
 	["land_canisterfuel_f", 2],
 	["land_metalbarrel_f", 5],
 	["land_portable_generator_f", 6],
 	["land_waterbarrel_f", 15],
 	["land_watertank_f", 20],
 	["land_campingchair_v1_f", 1],
 	["land_campingchair_v2_f", 1],
 	["land_campingtable_f", 2],
 	["land_campingtable_small_f", 1],
 	["land_camping_light_off_f", 1],
 	["land_cargobox_v1_f", 15],
 	["land_fieldtoilet_f", 4],
 	["land_ground_sheet_folded_f", 1],
 	["land_mapboard_f", 3],
 	["land_plasticbarrier_03_f", 2],
 	["land_redwhitepole_f", 1],
 	["land_sink_f", 5],
 	["land_sleeping_bag_folded_f", 1],
 	["land_toiletbox_f", 4],
 	["land_woodentable_large_f", 3],
 	["land_woodentable_small_f", 2],
 	["pole_f", 1],
 	["roadcone_f", 1],
 	["gastank_base_f", 2],
 	["tooltrolley_base_f", 3],
 	["land_weldingtrolley_01_f", 4],
 	["pallettrolley_01_base_f", 3],
 	["land_mobilelandingplatform_01_f", 10],
 	["windsock_01_f", 2],
 	["cargo10_base_f", 45],
 	["land_portablehelipadlight_01_f", 1],
 	["metalcase_01_base_f", 5],
 	["plasticcase_01_base_f", 5],
 	["cargonet_01_base_f", 16],
 	["flexibletank_base_f", 2],
 	["pod_heli_transport_04_base_f", 200],
 	["ka137_mg_pmc", 45],
 	["ka137_pmc", 45],
 	["pchela1t", 45],
 	["atv_base_ep1", 40],
 	["mmt_base", 8],
 	["m1030", 30],
 	["tt650_base", 30],
 	["stinger_pod", 15],
 	["stinger_pod_us_ep1", 15],
 	["tow_tripod", 10],
 	["tow_tripod_base", 10],
 	["m119", 50],
 	["d30_base", 50],
 	["zu23_base", 50],
 	["warfarebmgnest_m240_base", 10],
 	["uh1wreck", 200],
 	["uh60_wreck_ep1", 200],
 	["rubberboat", 40],
 	["pbx_acr", 40],
 	["concrete_wall_ep1", 3],
 	["fencewood", 1],
 	["fencewoodpalet", 1],
 	["wire", 2],
 	["fire", 1],
 	["flagcarriersmall", 1],
 	["fort_razorwire", 2],
 	["gunrack1", 2],
 	["base_warfarebbarrier5x", 3],
 	["base_warfarebbarrier10x", 6],
 	["base_warfarebbarrier10xtall", 12],
 	["base_warfarebbarrier5xpreview", 2],
 	["land_camonet_east", 2],
 	["land_camonet_nato", 2],
 	["land_fire", 1],
 	["land_fire_barrel", 3],
 	["land_fort_watchtower", 20],
 	["land_guardshed", 3],
 	["land_misc_cargo1ao", 120],
 	["land_misc_cargo1a_ep1", 120],
 	["land_misc_cargo1ao_ep1", 120],
 	["land_misc_cargo1b", 120],
 	["land_misc_cargo1b_ep1", 120],
 	["land_misc_cargo1bo", 120],
 	["land_misc_cargo1c", 120],
 	["land_misc_cargo1c_ep1", 120],
 	["land_misc_cargo1d", 120],
 	["land_misc_cargo1d_ep1", 120],
 	["land_misc_cargo1e", 120],
 	["land_misc_cargo1e_ep1", 120],
 	["land_misc_cargo1f", 120],
 	["land_misc_cargo1g", 120],
 	["land_misc_cargomarket1a_ep1", 120],
 	["land_woodenramp", 2],
 	["land_fort_bagfence_corner", 3],
 	["land_fort_bagfence_long", 2],
 	["land_fort_bagfence_round", 4],
 	["land_fort_rampart", 4],
 	["land_fortified_nest_big", 20],
 	["land_fortified_nest_small", 10],
 	["land_cncblock", 2],
 	["land_cncblock_d", 2],
 	["land_cncblock_stripes", 2],
 	["land_hbarrier_large", 4],
 	["land_bagfencecorner", 2],
 	["land_hbarrier1", 1],
 	["land_hbarrier3", 2],
 	["land_hbarrier5", 3],
 	["land_toilet", 3],
 	["paletabase", 2],
 	["roadbarrier_light", 2],
 	["targettraining", 2],
 	["warfarebunkersign", 3],
 	["zavoraanim", 2],
 	["base_warfarebcontructionsite", 120],
 	["fortress1", 10],
 	["hedgehog", 3],
 	["land_prebehlavka", 3],
 	["land_prolejzacka", 2],
 	["ammocrate_nointeractive_", 7],
 	["misc_cargo_cont_net1", 25],
 	["misc_cargo_cont_small", 75],
 	["misc_cargo_cont_small2", 60],
 	["shed", 2],
 	["target", 2],
 	["guerillacachebox", 5],
 	["specialweaponsbox", 10],
 	["rubasicammunitionbox", 5],
 	["rubasicweaponsbox", 15],
 	["ruspecialweaponsbox", 12],
 	["ruvehiclebox", 50],
 	["ammobox_pmc", 5],
 	["baf_vehiclebox", 30],
 	["czbasicweapons_ep1", 5],
 	["gerbasicweapons_ep1", 5],
 	["guerillacachebox_ep1", 5],
 	["tkbasicammunitionbox_ep1", 5],
 	["tkvehiclebox_ep1", 40],
 	["tkbasicweapons_ep1", 5],
 	["tklaunchers_ep1", 5],
 	["tkspecialweapons_ep1", 5],
 	["unbasicammunitionbox_ep1", 5],
 	["unbasicweapons_ep1", 5],
 	["usbasicammunitionbox_ep1", 5],
 	["usvehiclebox_ep1", 30],
 	["usbasicweapons_ep1", 5],
 	["uslaunchers_ep1", 5],
 	["usspecialweapons_ep1", 8],
 	["usbasicammunitionbox", 5],
 	["usvehiclebox", 20],
 	["targetgrenadbase", 5],
 	["wallmap", 2],
 	["foldchair", 1],
 	["woodchair", 1],
 	["foldtable", 2],
 	["land_barrel_empty", 2],
 	["land_barrel_sand", 2],
 	["land_barrel_water", 2],
 	["land_conelight", 1],
 	["barrel1", 2],
 	["barrel2", 2],
 	["barrel3", 2],
 	["barrel4", 2],
 	["barrel5", 2],
 	["barrel6", 2],
 	["wooden_barrel", 2],
 	["fuel_can", 1],
 	["notice_board", 2],
 	["roadcone", 1],
 	["sign_danger", 2],
 	["smalltable", 2],
 	["small_items", 1],
 	["land_shelf_ep1", 2],
 	["r3f_uniformbox", 5],
 	["r3f_weaponstock", 5],
 	["exile_container_supplybox", 25],
 	["i_cargonet_01_ammo_f", 25],
 	["box_nato_wps_f", 15],
 	["box_nato_ammoord_f", 15],
 	["cup_b_pchela1t_cdf", 25],
 	["cup_b_m1030", 25],
 	["exile_bike_oldbike", 15],
 	["exile_bike_mountainbike", 15],
 	["exile_bike_quadbike_black", 25],
 	["exile_bike_quadbike_blue", 25],
 	["exile_bike_quadbike_red", 25],
 	["exile_bike_quadbike_white", 15],
 	["exile_bike_quadbike_nato", 25],
 	["exile_bike_quadbike_csat", 25],
 	["exile_bike_quadbike_fia", 25],
 	["exile_bike_quadbike_guerilla01", 25],
 	["exile_bike_quadbike_guerilla02", 25],
 	["exile_car_kart_bluking", 25],
 	["exile_car_kart_redstone", 25],
 	["exile_car_kart_vrana", 25],
 	["exile_car_kart_green", 25],
 	["exile_car_kart_blue", 25],
 	["exile_car_kart_orange", 25],
 	["exile_car_kart_white", 25],
 	["exile_car_kart_yellow", 25],
 	["exile_car_kart_black", 25]	
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[

 	"uav_01_base_f",
 	"reammobox_f",
 	"staticweapon",
 	"land_camping_light_f",
 	"roadcone_l_f",
 	"roadbarrier_small_f",
 	"rubber_duck_base_f",
 	"camping_base_f",
 	"flagsmall_f",
 	"hbarrier_base_f",
 	"helper_base_f",
 	"helih",
 	"land_portablelight_single_f",
 	"land_metalbarrel_empty_f",
 	"land_campfire_f",
 	"land_fireplace_f",
 	"land_obstacle_bridge_f",
 	"land_razorwire_f",
 	"land_sign_mines_f",
 	"land_pallet_milboxes_f",
 	"land_paperbox_closed_f",
 	"land_paperbox_open_empty_f",
 	"land_paperbox_open_full_f",
 	"land_bargate_f",
 	"land_cncbarriermedium4_f",
 	"land_cncbarriermedium_f",
 	"land_cncbarrier_f",
 	"land_cncbarrier_stripes_f",
 	"land_cncwall1_f",
 	"land_cncwall4_f",
 	"land_mil_concretewall_f",
 	"land_shoot_house_wall_f",
 	"sign_f",
 	"land_plasticbarrier_01_f",
 	"land_plasticbarrier_02_f",
 	"bagbunker_base_f",
 	"bagfence_base_f",
 	"flagcarriercore",
 	"reammobox_f",
 	"targetbase",
 	"land_pierladder_f",
 	"metal_pole_f",
 	"arrowmarker_r_f",
 	"land_pallet_f",
 	"land_pallets_stack_f",
 	"furniture_base_f",
 	"items_base_f",
 	"land_campingchair_v1_f",
 	"land_campingchair_v2_f",
 	"land_campingtable_f",
 	"land_campingtable_small_f",
 	"land_camping_light_off_f",
 	"land_cargobox_v1_f",
 	"land_fieldtoilet_f",
 	"land_ground_sheet_folded_f",
 	"land_mapboard_f",
 	"land_plasticbarrier_03_f",
 	"land_redwhitepole_f",
 	"land_sink_f",
 	"land_sleeping_bag_folded_f",
 	"land_toiletbox_f",
 	"land_woodentable_large_f",
 	"land_woodentable_small_f",
 	"pole_f",
 	"roadcone_f",
 	"gastank_base_f",
 	"tooltrolley_base_f",
 	"land_weldingtrolley_01_f",
 	"pallettrolley_01_base_f",
 	"windsock_01_f",
 	"land_mobilelandingplatform_01_f",
 	"land_portablehelipadlight_01_f",
 	"flexibletank_base_f",
 	"ka137_mg_pmc",
 	"ka137_pmc",
 	"mmt_base",
 	"rubberboat",
 	"pbx_acr",
 	"concrete_wall_ep1",
 	"fencewood",
 	"fencewoodpalet",
 	"wire",
 	"fire",
 	"flagcarriersmall",
 	"fort_razorwire",
 	"gunrack1",
 	"base_warfarebbarrier5x",
 	"land_camonet_east",
 	"land_camonet_nato",
 	"land_fire",
 	"land_fort_watchtower",
 	"land_guardshed",
 	"land_woodenramp",
 	"land_fort_bagfence_corner",
 	"land_fort_bagfence_long",
 	"land_fort_bagfence_round",
 	"land_fort_rampart",
 	"land_fortified_nest_big",
 	"land_fortified_nest_small",
 	"land_cncblock",
 	"land_cncblock_d",
 	"land_cncblock_stripes",
 	"land_hbarrier_large",
 	"land_bagfencecorner",
 	"land_toilet",
 	"paletabase",
 	"roadbarrier_light",
 	"targettraining",
 	"warfarebunkersign",
 	"zavoraanim",
 	"fortress1",
 	"hedgehog",
 	"land_prebehlavka",
 	"land_prolejzacka",
 	"ammocrate_nointeractive_",
 	"misc_cargo_cont_net1",
 	"shed",
 	"target",
 	"guerillacachebox",
 	"rubasicammunitionbox",
 	"ammobox_pmc",
 	"czbasicweapons_ep1",
 	"gerbasicweapons_ep1",
 	"guerillacachebox_ep1",
 	"tkbasicammunitionbox_ep1",
 	"tkbasicweapons_ep1",
 	"tklaunchers_ep1",
 	"tkspecialweapons_ep1",
 	"unbasicammunitionbox_ep1",
 	"unbasicweapons_ep1",
 	"usbasicammunitionbox_ep1",
 	"usbasicweapons_ep1",
 	"uslaunchers_ep1",
 	"usspecialweapons_ep1",
 	"usbasicammunitionbox",
 	"wallmap",
 	"foldchair",
 	"woodchair",
 	"foldtable",
 	"land_barrel_empty",
 	"land_barrel_sand",
 	"land_barrel_water",
 	"land_conelight",
 	"barrel1",
 	"barrel2",
 	"barrel3",
 	"barrel4",
 	"barrel5",
 	"barrel6",
 	"wooden_barrel",
 	"fuel_can",
 	"notice_board",
 	"roadcone",
 	"sign_danger",
 	"smalltable",
 	"small_items",
 	"land_shelf_ep1",
 	"exile_container_supplybox",
 	"box_ind_ammoveh_f",
 	"i_cargonet_01_ammo_f",
 	"box_nato_wps_f",
 	"box_nato_ammoord_f",
 	"cup_b_pchela1t_cdf",
 	"cup_b_m1030",
 	"exile_bike_oldbike",
 	"exile_bike_mountainbike"	
];
