R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
 	"exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ikarus_blue",
 	"exile_car_ikarus_red",
 	"exile_car_ikarus_party",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_towtractor_white",
 	"exile_car_octavius_white",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_hemmt",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"exile_car_tempest",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"exile_car_prowlerlight",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"

];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
 	"exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
	"exile_bike_quadbike_black",
 	"exile_bike_quadbike_blue",
 	"exile_bike_quadbike_red",
 	"exile_bike_quadbike_white",
 	"exile_bike_quadbike_nato",
 	"exile_bike_quadbike_csat",
 	"exile_bike_quadbike_fia",
 	"exile_bike_quadbike_guerilla01",
 	"exile_bike_quadbike_guerilla02",
 	"exile_car_kart_bluking",
 	"exile_car_kart_redstone",
 	"exile_car_kart_vrana",
 	"exile_car_kart_green",
 	"exile_car_kart_blue",
 	"exile_car_kart_orange",
 	"exile_car_kart_white",
 	"exile_car_kart_yellow",
 	"exile_car_kart_black",
 	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ikarus_blue",
 	"exile_car_ikarus_red",
 	"exile_car_ikarus_party",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_towtractor_white",
 	"exile_car_octavius_white",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_hemmt",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"exile_car_tempest",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"exile_car_prowlerlight",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"
                        
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
        "exile_car_brdm2_hq",
 	"exile_car_ifrit",
 	"exile_car_hunter",
 	"exile_car_strider",
	"exile_car_towtractor_white",
 	"exile_car_octavius_white",
 	"exile_car_hemmt",
 	"exile_car_tempest",
	"exile_bike_quadbike_black",
 	"exile_bike_quadbike_blue",
 	"exile_bike_quadbike_white",
 	"exile_bike_quadbike_nato",
 	"exile_bike_quadbike_csat",
 	"exile_bike_quadbike_fia",
 	"exile_bike_quadbike_guerilla01",
 	"exile_bike_quadbike_guerilla02",
 	"exile_bike_quadbike_red",
 	"exile_car_kart_bluking",
 	"exile_car_kart_redstone",
 	"exile_car_kart_vrana",
 	"exile_car_kart_green",
 	"exile_car_kart_blue",
 	"exile_car_kart_orange",
 	"exile_car_kart_white",
 	"exile_car_kart_yellow",
 	"exile_car_kart_black",
 	"exile_car_hatchback_beige",
 	"exile_car_hatchback_green",
 	"exile_car_hatchback_blue",
 	"exile_car_hatchback_bluecustom",
 	"exile_car_hatchback_beigecustom",
 	"exile_car_hatchback_yellow",
 	"exile_car_hatchback_grey",
 	"exile_car_hatchback_black",
 	"exile_car_hatchback_dark",
 	"exile_car_hatchback_rusty1",
 	"exile_car_hatchback_rusty2",
 	"exile_car_hatchback_rusty3",
 	"exile_car_golf_red",
 	"exile_car_golf_black",
 	"exile_car_ural_open_blue",
 	"exile_car_ural_open_yellow",
 	"exile_car_ural_open_worker",
 	"exile_car_ural_open_military",
 	"exile_car_ural_covered_blue",
 	"exile_car_ural_covered_yellow",
 	"exile_car_ural_covered_worker",
 	"exile_car_ural_covered_military",
 	"exile_car_v3s_open",
 	"exile_car_v3s_covered",
 	"exile_car_suvxl_black",
 	"exile_car_tractor_red",
 	"exile_car_oldtractor_red",
 	"exile_car_octavius_black",
 	"exile_car_uaz_green",
 	"exile_car_uaz_open_green",
 	"exile_car_landrover_red",
 	"exile_car_landrover_urban",
 	"exile_car_landrover_green",
 	"exile_car_landrover_sand",
 	"exile_car_landrover_desert",
 	"exile_car_landrover_ambulance_green",
 	"exile_car_landrover_ambulance_desert",
 	"exile_car_landrover_ambulance_sand",
 	"exile_car_lada_green",
 	"exile_car_lada_taxi",
 	"exile_car_lada_red",
 	"exile_car_lada_white",
 	"exile_car_lada_hipster",
 	"exile_car_volha_blue",
 	"exile_car_volha_white",
 	"exile_car_volha_black",
 	"exile_car_hatchback_sport_red",
 	"exile_car_hatchback_sport_blue",
 	"exile_car_hatchback_sport_orange",
 	"exile_car_hatchback_sport_white",
 	"exile_car_hatchback_sport_beige",
 	"exile_car_hatchback_sport_green",
 	"exile_car_offroad_red",
 	"exile_car_offroad_beige",
 	"exile_car_offroad_white",
 	"exile_car_offroad_blue",
 	"exile_car_offroad_darkred",
 	"exile_car_offroad_bluecustom",
 	"exile_car_offroad_guerilla01",
 	"exile_car_offroad_guerilla02",
 	"exile_car_offroad_guerilla03",
 	"exile_car_offroad_guerilla04",
 	"exile_car_offroad_guerilla05",
 	"exile_car_offroad_guerilla06",
 	"exile_car_offroad_guerilla07",
 	"exile_car_offroad_guerilla08",
 	"exile_car_offroad_guerilla09",
 	"exile_car_offroad_guerilla10",
 	"exile_car_offroad_guerilla11",
 	"exile_car_offroad_guerilla12",
 	"exile_car_offroad_rusty1",
 	"exile_car_offroad_rusty2",
 	"exile_car_offroad_rusty3",
 	"exile_car_offroad_repair_civillian",
 	"exile_car_offroad_repair_red",
 	"exile_car_offroad_repair_beige",
 	"exile_car_offroad_repair_white",
 	"exile_car_offroad_repair_blue",
 	"exile_car_offroad_repair_darkred",
 	"exile_car_offroad_repair_bluecustom",
 	"exile_car_offroad_repair_guerilla01",
 	"exile_car_offroad_repair_guerilla02",
 	"exile_car_offroad_repair_guerilla03",
 	"exile_car_offroad_repair_guerilla04",
 	"exile_car_offroad_repair_guerilla05",
 	"exile_car_offroad_repair_guerilla06",
 	"exile_car_offroad_repair_guerilla07",
 	"exile_car_offroad_repair_guerilla08",
 	"exile_car_offroad_repair_guerilla09",
 	"exile_car_offroad_repair_guerilla10",
 	"exile_car_offroad_repair_guerilla11",
 	"exile_car_offroad_repair_guerilla12",
 	"exile_car_suv_red",
 	"exile_car_suv_black",
 	"exile_car_suv_grey",
 	"exile_car_suv_orange",
 	"exile_car_btr40_green",
 	"exile_car_btr40_camo",
 	"exile_car_hmmwv_mev_green",
 	"exile_car_hmmwv_mev_desert",
 	"exile_car_hmmwv_una_green",
 	"exile_car_hmmwv_una_desert",
 	"exile_car_van_black",
 	"exile_car_van_white",
 	"exile_car_van_red",
 	"exile_car_van_guerilla01",
 	"exile_car_van_guerilla02",
 	"exile_car_van_guerilla03",
 	"exile_car_van_guerilla04",
 	"exile_car_van_guerilla05",
 	"exile_car_van_guerilla06",
 	"exile_car_van_guerilla07",
 	"exile_car_van_guerilla08",
 	"exile_car_van_box_black",
 	"exile_car_van_box_white",
 	"exile_car_van_box_red",
 	"exile_car_van_box_guerilla01",
 	"exile_car_van_box_guerilla02",
 	"exile_car_van_box_guerilla03",
 	"exile_car_van_box_guerilla04",
 	"exile_car_van_box_guerilla05",
 	"exile_car_van_box_guerilla06",
 	"exile_car_van_box_guerilla07",
 	"exile_car_van_box_guerilla08",
 	"exile_car_van_fuel_black",
 	"exile_car_van_fuel_white",
 	"exile_car_van_fuel_red",
 	"exile_car_van_fuel_guerilla01",
 	"exile_car_van_fuel_guerilla02",
 	"exile_car_van_fuel_guerilla03",
 	"exile_car_zamak",
 	"exile_car_prowlerlight",
 	"exile_car_prowlerunarmed",
 	"exile_car_qilinunarmed",
 	"exile_car_mb4wd",
 	"exile_car_mb4wdopen"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
  
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
 	["exile_car_brdm2_hq", 50],
 	["exile_car_ifrit", 50],
 	["exile_car_hunter", 50],
 	["exile_car_strider", 50],
	["exile_bike_quadbike_black", 15],
 	["exile_bike_quadbike_blue", 15],
 	["exile_bike_quadbike_red", 15],
 	["exile_bike_quadbike_white", 15],
 	["exile_bike_quadbike_nato", 15],
 	["exile_bike_quadbike_csat", 15],
 	["exile_bike_quadbike_fia", 15],
 	["exile_bike_quadbike_guerilla01", 15],
 	["exile_bike_quadbike_guerilla02", 15],
 	["exile_car_hatchback_beige", 15],
 	["exile_car_hatchback_green", 15],
 	["exile_car_hatchback_blue", 15],
 	["exile_car_hatchback_bluecustom", 15],
 	["exile_car_hatchback_beigecustom", 15],
 	["exile_car_hatchback_yellow", 15],
 	["exile_car_hatchback_grey", 15],
 	["exile_car_hatchback_black", 15],
 	["exile_car_hatchback_dark", 15],
 	["exile_car_hatchback_rusty1", 15],
 	["exile_car_hatchback_rusty2", 15],
 	["exile_car_hatchback_rusty3", 15],
 	["exile_car_golf_red", 15],
 	["exile_car_golf_black", 15],
 	["exile_car_ikarus_blue", 200],
 	["exile_car_ikarus_red", 200],
 	["exile_car_ikarus_party", 200],
 	["exile_car_ural_open_blue", 75],
 	["exile_car_ural_open_yellow", 75],
 	["exile_car_ural_open_worker", 75],
 	["exile_car_ural_open_military", 75],
 	["exile_car_ural_covered_blue", 75],
 	["exile_car_ural_covered_yellow", 75],
 	["exile_car_ural_covered_worker", 75],
 	["exile_car_ural_covered_military", 75],
 	["exile_car_v3s_open", 75],
 	["exile_car_v3s_covered", 75],
 	["exile_car_suvxl_black", 50],
 	["exile_car_octavius_white", 15],
 	["exile_car_octavius_black", 15],
 	["exile_car_uaz_green", 25],
 	["exile_car_uaz_open_green", 25],
 	["exile_car_landrover_red", 25],
 	["exile_car_landrover_urban", 25],
 	["exile_car_landrover_green", 25],
 	["exile_car_landrover_sand", 25],
 	["exile_car_landrover_desert", 25],
 	["exile_car_landrover_ambulance_green", 50],
 	["exile_car_landrover_ambulance_desert", 50],
 	["exile_car_landrover_ambulance_sand", 50],
 	["exile_car_lada_green", 15],
 	["exile_car_lada_taxi", 15],
 	["exile_car_lada_red", 15],
 	["exile_car_lada_white", 15],
 	["exile_car_lada_hipster", 15],
 	["exile_car_volha_blue", 15],
 	["exile_car_volha_white", 15],
 	["exile_car_volha_black", 15],
 	["exile_car_hatchback_sport_red", 15],
 	["exile_car_hatchback_sport_blue", 15],
 	["exile_car_hatchback_sport_orange", 15],
 	["exile_car_hatchback_sport_white", 15],
 	["exile_car_hatchback_sport_beige", 15],
 	["exile_car_hatchback_sport_green", 15],
 	["exile_car_hemmt", 125],
 	["exile_car_offroad_red", 25],
 	["exile_car_offroad_beige", 25],
 	["exile_car_offroad_white", 25],
 	["exile_car_offroad_blue", 25],
 	["exile_car_offroad_darkred", 25],
 	["exile_car_offroad_bluecustom", 25],
 	["exile_car_offroad_guerilla01", 25],
 	["exile_car_offroad_guerilla02", 25],
 	["exile_car_offroad_guerilla03", 25],
 	["exile_car_offroad_guerilla04", 25],
 	["exile_car_offroad_guerilla05", 25],
 	["exile_car_offroad_guerilla06", 25],
 	["exile_car_offroad_guerilla07", 25],
 	["exile_car_offroad_guerilla08", 25],
 	["exile_car_offroad_guerilla09", 25],
 	["exile_car_offroad_guerilla10", 25],
 	["exile_car_offroad_guerilla11", 25],
 	["exile_car_offroad_guerilla12", 25],
 	["exile_car_offroad_rusty1", 25],
 	["exile_car_offroad_rusty2", 25],
 	["exile_car_offroad_rusty3", 25],
 	["exile_car_offroad_repair_civillian", 25],
 	["exile_car_offroad_repair_red", 25],
 	["exile_car_offroad_repair_beige", 25],
 	["exile_car_offroad_repair_white", 25],
 	["exile_car_offroad_repair_blue", 25],
 	["exile_car_offroad_repair_darkred", 25],
 	["exile_car_offroad_repair_bluecustom", 25],
 	["exile_car_offroad_repair_guerilla01", 25],
 	["exile_car_offroad_repair_guerilla02", 25],
 	["exile_car_offroad_repair_guerilla03", 25],
 	["exile_car_offroad_repair_guerilla04", 25],
 	["exile_car_offroad_repair_guerilla05", 25],
 	["exile_car_offroad_repair_guerilla06", 25],
 	["exile_car_offroad_repair_guerilla07", 25],
 	["exile_car_offroad_repair_guerilla08", 25],
 	["exile_car_offroad_repair_guerilla09", 25],
 	["exile_car_offroad_repair_guerilla10", 25],
 	["exile_car_offroad_repair_guerilla11", 25],
 	["exile_car_offroad_repair_guerilla12", 25],
 	["exile_car_suv_red", 15],
 	["exile_car_suv_black", 15],
 	["exile_car_suv_grey", 15],
 	["exile_car_suv_orange", 15],
 	["exile_car_btr40_green", 25],
 	["exile_car_btr40_camo", 25],
 	["exile_car_hmmwv_mev_green", 25],
 	["exile_car_hmmwv_mev_desert", 25],
 	["exile_car_hmmwv_una_green", 25],
 	["exile_car_hmmwv_una_desert", 25],
 	["exile_car_tempest", 125],
 	["exile_car_van_black", 50],
 	["exile_car_van_white", 50],
 	["exile_car_van_red", 50],
 	["exile_car_van_guerilla01", 50],
 	["exile_car_van_guerilla02", 50],
 	["exile_car_van_guerilla03", 50],
 	["exile_car_van_guerilla04", 50],
 	["exile_car_van_guerilla05", 50],
 	["exile_car_van_guerilla06", 50],
 	["exile_car_van_guerilla07", 50],
 	["exile_car_van_guerilla08", 25],
 	["exile_car_van_box_black", 50],
 	["exile_car_van_box_white", 50],
 	["exile_car_van_box_red", 50],
 	["exile_car_van_box_guerilla01", 50],
 	["exile_car_van_box_guerilla02", 50],
 	["exile_car_van_box_guerilla03", 50],
 	["exile_car_van_box_guerilla04", 50],
 	["exile_car_van_box_guerilla05", 50],
 	["exile_car_van_box_guerilla06", 50],
 	["exile_car_van_box_guerilla07", 50],
 	["exile_car_van_box_guerilla08", 50],
 	["exile_car_zamak", 75],
 	["exile_car_prowlerlight", 25],
 	["exile_car_prowlerunarmed", 25],
 	["exile_car_qilinunarmed", 25],
 	["exile_car_mb4wd", 15],
 	["exile_car_mb4wdopen", 15]

];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
   	["exile_bike_quadbike_black", 25],
 	["exile_bike_quadbike_blue", 25],
 	["exile_bike_quadbike_red", 25],
 	["exile_bike_quadbike_white", 25],
 	["exile_bike_quadbike_nato", 25],
 	["exile_bike_quadbike_csat", 25],
 	["exile_bike_quadbike_fia", 25],
 	["exile_bike_quadbike_guerilla01", 25],
 	["exile_bike_quadbike_guerilla02", 25],
 	["exile_car_kart_bluking", 25],
 	["exile_car_kart_redstone", 25],
 	["exile_car_kart_vrana", 25],
 	["exile_car_kart_green", 25],
 	["exile_car_kart_blue", 25],
 	["exile_car_kart_orange", 25],
 	["exile_car_kart_white", 25],
 	["exile_car_kart_yellow", 25],
 	["exile_car_kart_black", 25]
];
