R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	"cup_b_f35b_aa_usmc",
 	"cup_b_f35b_cas_usmc",
 	"cup_b_f35b_lgb_usmc",
 	"cup_b_f35b_aa_baf",
 	"cup_b_f35b_cas_baf",
 	"cup_b_f35b_lgb_baf",
 	"cup_b_l39_rkt_cz",
 	"cup_b_l39_bmb_cz",
 	"cup_b_su34_lgb_cdf",
 	"cup_b_su34_agm_cdf",
 	"cup_b_a10_cas_usa",
 	"cup_b_a10_at_usa",
 	"cup_b_av8b_cap_usmc",
 	"cup_b_av8b_gbu12_usmc",
 	"cup_b_av8b_mk82_usmc",
 	"cup_b_av8b_agm_usmc",
 	"cup_b_gr9_cap_gb",
 	"cup_b_gr9_mk82_gb",
 	"cup_b_gr9_gbu12_gb",
 	"cup_b_gr9_agm_gb",
 	"cup_b_su25_cdf",
 	"cup_b_mv22_usmc_rampgun",
	"cup_b_ah1z_usmc",
 	"cup_b_ah1z_escort_usmc",
 	"cup_b_ah64d_es_usa",
 	"cup_b_ah64d_mr_usa",
 	"cup_b_aw159_hellfire_gb",
 	"cup_b_aw159_cannon_gb",
 	"cup_b_aw159_hellfire_rn_grey",
 	"cup_b_aw159_cannon_rn_grey",
 	"cup_b_aw159_hellfire_rn_blackcat",
 	"cup_b_aw159_cannon_rn_blackcat",
 	"cup_b_ch47f_usa",
 	"cup_b_ch47f_viv_usa",
 	"cup_b_ch47f_gb",
 	"cup_b_ch47f_viv_gb",
 	"cup_b_mh60s_usmc",
 	"cup_b_mi24_d_cdf",
 	"cup_b_mi35_cz",
 	"cup_b_mi35_cz_des",
 	"cup_b_mi35_cz_ram",
 	"cup_b_mi35_cz_tiger",
 	"cup_b_mi35_cz_dark",
 	"cup_b_mi17_cdf",
 	"cup_b_mi171sh_acr",
 	"cup_b_merlin_hc3_armed_gb",
 	"cup_b_merlin_hc3a_armed_gb",
 	"cup_b_uh1y_gunship_usmc",
 	"cup_b_uh60m_ffv_us",
 	"cup_b_uh60l_ffv_us",
 	"cup_b_ah6j_escort_usa",
 	"cup_b_ah6j_at_usa",
 	"cup_b_ah6j_mp_usa",
 	"cup_b_ah6j_escort19_usa",
 	"cup_i_mi24_mk4_aaf",
 	"cup_o_mi24_mk4_csat_t",
 	"cup_i_mi24_mk4_ion",
 	"cup_i_mi24_mk4_un",
	"cup_b_c130j_usmc",
 	"cup_b_c130j_cargo_usmc",
 	"cup_b_c130j_gb",
 	"cup_b_c130j_cargo_gb",
 	"cup_b_mv22_usmc",
 	"cup_b_mv22_viv_usmc",
	"cup_b_uh60m_unarmed_us",
 	"cup_b_uh60l_unarmed_us",
 	"cup_b_uh60m_unarmed_ffv_us",
 	"cup_b_uh60l_unarmed_ffv_us",
 	"cup_b_uh60m_unarmed_ffv_mev_us",
 	"cup_b_uh60l_unarmed_ffv_mev_us",
 	"cup_b_mh6j_usa",
 	"cup_b_aw159_unarmed_gb",
 	"cup_b_wildcat_unarmed_rn_blackcat",
 	"cup_b_mi6a_cdf",
 	"cup_b_mi6t_cdf",
 	"cup_b_mi17_viv_cdf",
 	"cup_b_mi17_medevac_cdf",
 	"cup_b_ch53e_usmc",
 	"cup_b_ch53e_viv_usmc",
 	"cup_b_ch53e_ger",
 	"cup_b_ch53e_viv_ger",
 	"cup_b_merlin_hc3_gb",
 	"cup_b_merlin_hc3_viv_gb",
 	"cup_b_merlin_hc3a_gb",
 	"cup_b_merlin_hc4_gb",
 	"cup_b_uh1y_una_usmc",
 	"cup_b_uh1y_mev_usmc",
 	"cup_b_ah6x_usa",
 	"cup_b_sa330_puma_hc1_baf",
 	"cup_b_sa330_puma_hc2_baf"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
	"cup_b_aw159_hellfire_gb",
 	"cup_b_aw159_cannon_gb",
 	"cup_b_aw159_hellfire_rn_grey",
 	"cup_b_aw159_cannon_rn_grey",
 	"cup_b_aw159_hellfire_rn_blackcat",
 	"cup_b_aw159_cannon_rn_blackcat",
 	"cup_b_ch47f_usa",
 	"cup_b_ch47f_viv_usa",
 	"cup_b_ch47f_gb",
 	"cup_b_ch47f_viv_gb",
 	"cup_b_mh60s_usmc",
 	"cup_b_mi24_d_cdf",
 	"cup_b_mi35_cz",
 	"cup_b_mi35_cz_des",
 	"cup_b_mi35_cz_ram",
 	"cup_b_mi35_cz_tiger",
 	"cup_b_mi35_cz_dark",
 	"cup_b_mi17_cdf",
 	"cup_b_mi171sh_acr",
 	"cup_b_merlin_hc3_armed_gb",
 	"cup_b_merlin_hc3a_armed_gb",
 	"cup_b_uh1y_gunship_usmc",
 	"cup_b_uh60m_ffv_us",
 	"cup_b_uh60l_ffv_us",
 	"cup_i_mi24_mk4_aaf",
 	"cup_o_mi24_mk4_csat_t",
 	"cup_i_mi24_mk4_ion",
 	"cup_i_mi24_mk4_un",
	"cup_b_uh60m_unarmed_us",
 	"cup_b_uh60l_unarmed_us",
 	"cup_b_uh60m_unarmed_ffv_us",
 	"cup_b_uh60l_unarmed_ffv_us",
 	"cup_b_uh60m_unarmed_ffv_mev_us",
 	"cup_b_uh60l_unarmed_ffv_mev_us",
 	"cup_b_aw159_unarmed_gb",
 	"cup_b_wildcat_unarmed_rn_blackcat",
 	"cup_b_mi6a_cdf",
 	"cup_b_mi6t_cdf",
 	"cup_b_mi17_viv_cdf",
 	"cup_b_mi17_medevac_cdf",
 	"cup_b_ch53e_usmc",
 	"cup_b_ch53e_viv_usmc",
 	"cup_b_ch53e_ger",
 	"cup_b_ch53e_viv_ger",
 	"cup_b_merlin_hc3_gb",
 	"cup_b_merlin_hc3_viv_gb",
 	"cup_b_merlin_hc3a_gb",
 	"cup_b_merlin_hc4_gb",
 	"cup_b_uh1y_una_usmc",
 	"cup_b_uh1y_mev_usmc",
 	"cup_b_sa330_puma_hc1_baf",
 	"cup_b_sa330_puma_hc2_baf"
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"cup_b_f35b_aa_usmc",
 	"cup_b_f35b_cas_usmc",
 	"cup_b_f35b_lgb_usmc",
 	"cup_b_f35b_aa_baf",
 	"cup_b_f35b_cas_baf",
 	"cup_b_f35b_lgb_baf",
 	"cup_b_l39_rkt_cz",
 	"cup_b_l39_bmb_cz",
 	"cup_b_su34_lgb_cdf",
 	"cup_b_su34_agm_cdf",
 	"cup_b_a10_cas_usa",
 	"cup_b_a10_at_usa",
 	"cup_b_av8b_cap_usmc",
 	"cup_b_av8b_gbu12_usmc",
 	"cup_b_av8b_mk82_usmc",
 	"cup_b_av8b_agm_usmc",
 	"cup_b_gr9_cap_gb",
 	"cup_b_gr9_mk82_gb",
 	"cup_b_gr9_gbu12_gb",
 	"cup_b_gr9_agm_gb",
 	"cup_b_su25_cdf"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["cup_b_aw159_hellfire_gb", 25],
 	["cup_b_aw159_cannon_gb", 25],
 	["cup_b_aw159_hellfire_rn_grey", 25],
 	["cup_b_aw159_cannon_rn_grey", 25],
 	["cup_b_aw159_hellfire_rn_blackcat", 25],
 	["cup_b_aw159_cannon_rn_blackcat", 25],
 	["cup_b_ch47f_usa", 125],
 	["cup_b_ch47f_viv_usa", 125],
 	["cup_b_ch47f_gb", 125],
 	["cup_b_ch47f_viv_gb", 125],
 	["cup_b_mh60s_usmc", 50],
 	["cup_b_mi24_d_cdf", 50],
 	["cup_b_mi35_cz", 50],
 	["cup_b_mi35_cz_des", 50],
 	["cup_b_mi35_cz_ram", 50],
 	["cup_b_mi35_cz_tiger", 50],
 	["cup_b_mi35_cz_dark", 50],
 	["cup_b_mi17_cdf", 75],
 	["cup_b_mi171sh_acr", 75],
 	["cup_b_merlin_hc3_armed_gb", 100],
 	["cup_b_merlin_hc3a_armed_gb", 100],
 	["cup_b_uh1y_gunship_usmc", 25],
 	["cup_b_uh60m_ffv_us", 50],
 	["cup_b_uh60l_ffv_us", 50],
 	["cup_b_ah6j_escort_usa", 15],
 	["cup_b_ah6j_at_usa", 15],
 	["cup_b_ah6j_mp_usa", 15],
 	["cup_b_ah6j_escort19_usa", 15],
 	["cup_i_mi24_mk4_aaf", 50],
 	["cup_o_mi24_mk4_csat_t", 50],
 	["cup_i_mi24_mk4_ion", 50],
 	["cup_i_mi24_mk4_un", 50],
	["cup_b_c130j_usmc", 150],
 	["cup_b_c130j_cargo_usmc", 150],
 	["cup_b_c130j_gb", 150],
 	["cup_b_c130j_cargo_gb", 150],
 	["cup_b_mv22_usmc", 100],
 	["cup_b_mv22_viv_usmc", 100],
	["cup_b_uh60m_unarmed_us", 50],
 	["cup_b_uh60l_unarmed_us", 50],
 	["cup_b_uh60m_unarmed_ffv_us", 50],
 	["cup_b_uh60l_unarmed_ffv_us", 50],
 	["cup_b_uh60m_unarmed_ffv_mev_us", 50],
 	["cup_b_uh60l_unarmed_ffv_mev_us", 50],
 	["cup_b_mh6j_usa", 15],
 	["cup_b_aw159_unarmed_gb", 25],
 	["cup_b_wildcat_unarmed_rn_blackcat", 25],
 	["cup_b_mi6a_cdf", 100],
 	["cup_b_mi6t_cdf", 100],
 	["cup_b_mi17_viv_cdf", 75],
 	["cup_b_mi17_medevac_cdf", 75],
 	["cup_b_ch53e_usmc", 75],
 	["cup_b_ch53e_viv_usmc", 75],
 	["cup_b_ch53e_ger", 75],
 	["cup_b_ch53e_viv_ger", 75],
 	["cup_b_merlin_hc3_gb", 75],
 	["cup_b_merlin_hc3_viv_gb", 75],
 	["cup_b_merlin_hc3a_gb", 75],
 	["cup_b_merlin_hc4_gb", 75],
 	["cup_b_uh1y_una_usmc", 25],
 	["cup_b_uh1y_mev_usmc", 25],
 	["cup_b_ah6x_usa", 15],
 	["cup_b_sa330_puma_hc1_baf", 50],
 	["cup_b_sa330_puma_hc2_baf", 50]

];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	
];
