R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
        "cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa",
	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_btr60_cdf",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
	"cup_b_bmp2_cdf",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_m1a1_woodland_us_army",
 	"cup_b_m1a1_des_us_army",
 	"cup_b_m1a2_tusk_mg_us_army",
 	"cup_b_m1a2_tusk_mg_des_us_army",
 	"cup_b_t72_cdf",
 	"cup_b_t72_cz",
 	"cup_b_zsu23_cdf",
 	"cup_i_t34_napa",
	"cup_b_hmmwv_unarmed_usmc",
 	"cup_b_hmmwv_unarmed_usa",
 	"cup_b_hmmwv_transport_usa",
 	"cup_b_hmmwv_terminal_usa",
 	"cup_b_hmmwv_ambulance_usmc",
 	"cup_b_hmmwv_ambulance_usa",
 	"cup_b_hmmwv_ambulance_acr",
 	"cup_b_lr_ambulance_cz_w",
 	"cup_b_lr_ambulance_cz_d",
 	"cup_b_lr_ambulance_gb_w",
 	"cup_b_lr_transport_cz_w",
 	"cup_b_lr_transport_cz_d",
 	"cup_b_lr_transport_gb_w",
 	"cup_b_lr_transport_gb_d",
 	"cup_b_uaz_open_acr",
 	"cup_b_uaz_open_cdf",
 	"cup_b_uaz_unarmed_cdf",
 	"cup_b_uaz_unarmed_acr",
 	"cup_b_mtvr_usa",
 	"cup_b_mtvr_usmc",
 	"cup_b_ural_cdf",
 	"cup_b_mtvr_ammo_usa",
 	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf",
 	"cup_b_ural_open_cdf",
 	"cup_b_ural_empty_cdf"
            
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
        "cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa,
	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_btr60_cdf",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
	"cup_b_bmp2_cdf",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_m1a1_woodland_us_army",
 	"cup_b_m1a1_des_us_army",
 	"cup_b_m1a2_tusk_mg_us_army",
 	"cup_b_m1a2_tusk_mg_des_us_army",
 	"cup_b_t72_cdf",
 	"cup_b_t72_cz",
 	"cup_b_zsu23_cdf",
 	"cup_i_t34_napa",
	"cup_b_hmmwv_unarmed_usmc",
 	"cup_b_hmmwv_unarmed_usa",
 	"cup_b_hmmwv_transport_usa",
 	"cup_b_hmmwv_terminal_usa",
 	"cup_b_hmmwv_ambulance_usmc",
 	"cup_b_hmmwv_ambulance_usa",
 	"cup_b_hmmwv_ambulance_acr",
 	"cup_b_lr_ambulance_cz_w",
 	"cup_b_lr_ambulance_cz_d",
 	"cup_b_lr_ambulance_gb_w",
 	"cup_b_lr_transport_cz_w",
 	"cup_b_lr_transport_cz_d",
 	"cup_b_lr_transport_gb_w",
 	"cup_b_lr_transport_gb_d",
 	"cup_b_uaz_open_acr",
 	"cup_b_uaz_open_cdf",
 	"cup_b_uaz_unarmed_cdf",
 	"cup_b_uaz_unarmed_acr",
 	"cup_b_mtvr_usa",
 	"cup_b_mtvr_usmc",
 	"cup_b_ural_cdf",
 	"cup_b_mtvr_ammo_usa",
 	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf",
 	"cup_b_ural_open_cdf",
 	"cup_b_ural_empty_cdf"

];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
   
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
        "cup_b_hmmwv_m2_usmc",
 	"cup_b_hmmwv_m2_usa",
 	"cup_b_hmmwv_m2_gpk_usa",
 	"cup_b_hmmwv_m2_gpk_acr",
 	"cup_b_hmmwv_dshkm_gpk_acr",
 	"cup_b_hmmwv_crows_m2_usa",
 	"cup_b_hmmwv_sov_usa",
 	"cup_b_hmmwv_mk19_usmc",
 	"cup_b_hmmwv_mk19_usa",
 	"cup_b_hmmwv_ags_gpk_acr",
 	"cup_b_hmmwv_crows_mk19_usa",
 	"cup_b_hmmwv_tow_usmc",
 	"cup_b_hmmwv_tow_usa",
 	"cup_b_hmmwv_m1114_usmc",
 	"cup_b_hmmwv_avenger_usmc",
 	"cup_b_hmmwv_avenger_usa",
 	"cup_b_lr_mg_cz_w",
 	"cup_b_lr_mg_gb_w",
 	"cup_b_lr_special_cz_w",
 	"cup_b_lr_special_des_cz_d",
 	"cup_b_lr_special_gmg_gb_w",
 	"cup_b_lr_special_gmg_gb_d",
 	"cup_b_lr_special_m2_gb_w",
 	"cup_b_lr_special_m2_gb_d",
 	"cup_b_baf_coyote_l2a1_d",
 	"cup_b_baf_coyote_l2a1_w",
 	"cup_b_baf_coyote_gmg_d",
 	"cup_b_baf_coyote_gmg_w",
 	"cup_b_jackal2_l2a1_gb_d",
 	"cup_b_jackal2_l2a1_gb_w",
 	"cup_b_jackal2_gmg_gb_d",
 	"cup_b_jackal2_gmg_gb_w",
 	"cup_b_uaz_mg_cdf",
 	"cup_b_uaz_mg_acr",
 	"cup_b_uaz_ags30_cdf",
 	"cup_b_uaz_ags30_acr",
 	"cup_b_uaz_spg9_cdf",
 	"cup_b_uaz_spg9_acr",
 	"cup_b_uaz_metis_cdf",
 	"cup_b_uaz_metis_acr",
 	"cup_i_ural_zu23_napa",
	"cup_b_brdm2_hq_cdf",
 	"cup_b_brdm2_hq_cz",
 	"cup_b_brdm2_hq_des",
 	"cup_b_brdm2_cdf",
 	"cup_b_brdm2_atgm_cdf",
 	"cup_b_brdm2_cz",
 	"cup_b_brdm2_cz_des",
 	"cup_b_btr60_cdf",
 	"cup_b_bmp2_amb_cdf",
 	"cup_b_bmp2_amb_cz",
 	"cup_b_bmp2_amb_cz_des",
 	"cup_b_dingo_cz_wdl",
 	"cup_b_dingo_cz_des",
 	"cup_b_dingo_ger_wdl",
 	"cup_b_dingo_ger_des",
 	"cup_b_dingo_gl_cz_wdl",
 	"cup_b_dingo_gl_cz_des",
 	"cup_b_dingo_gl_ger_wdl",
 	"cup_b_dingo_gl_ger_des",
 	"cup_b_mastiff_hmg_gb_d",
 	"cup_b_mastiff_hmg_gb_w",
 	"cup_b_mastiff_gmg_gb_d",
 	"cup_b_mastiff_gmg_gb_w",
 	"cup_b_mastiff_lmg_gb_d",
 	"cup_b_mastiff_lmg_gb_w",
 	"cup_b_ridgback_hmg_gb_d",
 	"cup_b_ridgback_hmg_gb_w",
 	"cup_b_ridgback_gmg_gb_d",
 	"cup_b_ridgback_gmg_gb_w",
 	"cup_b_ridgback_lmg_gb_d",
 	"cup_b_ridgback_lmg_gb_w",
 	"cup_b_wolfhound_hmg_gb_d",
 	"cup_b_wolfhound_hmg_gb_w",
 	"cup_b_wolfhound_gmg_gb_d",
 	"cup_b_wolfhound_gmg_gb_w",
 	"cup_b_wolfhound_lmg_gb_d",
 	"cup_b_wolfhound_lmg_gb_w",
 	"cup_b_rg31_m2_usmc",
 	"cup_b_rg31_m2_od_usmc",
 	"cup_b_rg31_m2_gc_usmc",
 	"cup_b_rg31_mk19_usmc",
 	"cup_b_rg31_mk19_od_usmc",
 	"cup_b_rg31e_m2_usmc",
 	"cup_b_m1133_mev_desert",
 	"cup_b_m1133_mev_desert_slat",
 	"cup_b_m1133_mev_woodland",
 	"cup_b_m1133_mev_woodland_slat",
	"cup_b_bmp2_cdf",
 	"cup_b_bmp_hq_cdf",
 	"cup_b_bmp2_cz",
 	"cup_b_bmp2_cz_des",
 	"cup_b_bmp_hq_cz",
 	"cup_b_bmp_hq_cz_des",
 	"cup_b_lav25_usmc",
 	"cup_b_lav25m240_usmc",
 	"cup_b_lav25_hq_usmc",
 	"cup_b_m1126_icv_m2_desert",
 	"cup_b_m1126_icv_m2_desert_slat",
 	"cup_b_m1126_icv_m2_woodland",
 	"cup_b_m1126_icv_m2_woodland_slat",
 	"cup_b_m1126_icv_mk19_desert",
 	"cup_b_m1126_icv_mk19_desert_slat",
 	"cup_b_m1126_icv_mk19_woodland",
 	"cup_b_m1126_icv_mk19_woodland_slat",
 	"cup_b_m1130_cv_m2_desert",
 	"cup_b_m1130_cv_m2_desert_slat",
 	"cup_b_m1130_cv_m2_woodland",
 	"cup_b_m1130_cv_m2_woodland_slat",
 	"cup_b_m1135_atgmv_desert",
 	"cup_b_m1135_atgmv_desert_slat",
 	"cup_b_m1135_atgmv_woodland",
 	"cup_b_m1135_atgmv_woodland_slat",
 	"cup_b_m1128_mgs_desert",
 	"cup_b_m1128_mgs_desert_slat",
 	"cup_b_m1128_mgs_woodland",
 	"cup_b_m1128_mgs_woodland_slat",
 	"cup_b_aav_usmc",
 	"cup_b_fv432_bulldog_gb_d",
 	"cup_b_fv432_bulldog_gb_w",
 	"cup_b_fv432_bulldog_gb_d_rws",
 	"cup_b_fv432_bulldog_gb_w_rws",
 	"cup_b_fv510_gb_d_slat",
 	"cup_b_fv510_gb_w_slat",
 	"cup_b_fv510_gb_d",
 	"cup_b_fv510_gb_w",
 	"cup_b_m113_usa",
 	"cup_b_m163_usa",
 	"cup_b_mcv80_gb_d_slat",
 	"cup_b_mcv80_gb_w_slat",
 	"cup_b_mcv80_gb_d",
 	"cup_b_mcv80_gb_w",
 	"cup_b_m2bradley_usa_d",
 	"cup_b_m2bradley_usa_w",
 	"cup_b_m2a3bradley_usa_d",
 	"cup_b_m2a3bradley_usa_w",
 	"cup_b_m7bradley_usa_d",
 	"cup_b_m6linebacker_usa_d",
 	"cup_b_m6linebacker_usa_w",
 	"cup_b_zsu23_cdf",
	"cup_b_mtvr_refuel_usa",
 	"cup_b_mtvr_repair_usa",
 	"cup_b_mtvr_ammo_usmc",
 	"cup_b_mtvr_refuel_usmc",
 	"cup_b_mtvr_repair_usmc",
 	"cup_b_ural_refuel_cdf",
 	"cup_b_ural_repair_cdf",
 	"cup_b_ural_reammo_cdf"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
        ["cup_b_hmmwv_m2_usmc", 25],
 	["cup_b_hmmwv_m2_usa", 25],
 	["cup_b_hmmwv_m2_gpk_usa", 25],
 	["cup_b_hmmwv_m2_gpk_acr", 25],
 	["cup_b_hmmwv_dshkm_gpk_acr", 25],
 	["cup_b_hmmwv_crows_m2_usa", 25],
 	["cup_b_hmmwv_sov_usa", 25],
 	["cup_b_hmmwv_mk19_usmc", 25],
 	["cup_b_hmmwv_mk19_usa", 25],
 	["cup_b_hmmwv_ags_gpk_acr", 25],
 	["cup_b_hmmwv_crows_mk19_usa", 25],
 	["cup_b_hmmwv_tow_usmc", 25],
 	["cup_b_hmmwv_tow_usa", 25],
 	["cup_b_hmmwv_m1114_usmc", 25],
 	["cup_b_lr_mg_cz_w", 25],
 	["cup_b_lr_mg_gb_w", 25],
 	["cup_b_lr_special_cz_w", 25],
 	["cup_b_lr_special_des_cz_d", 25],
 	["cup_b_lr_special_gmg_gb_w", 25],
 	["cup_b_lr_special_gmg_gb_d", 25],
 	["cup_b_lr_special_m2_gb_w", 25],
 	["cup_b_lr_special_m2_gb_d", 25],
 	["cup_b_baf_coyote_l2a1_d", 50],
 	["cup_b_baf_coyote_l2a1_w", 50],
 	["cup_b_baf_coyote_gmg_d", 50],
 	["cup_b_baf_coyote_gmg_w", 50],
 	["cup_b_jackal2_l2a1_gb_d", 25],
 	["cup_b_jackal2_l2a1_gb_w", 25],
 	["cup_b_jackal2_gmg_gb_d", 25],
 	["cup_b_jackal2_gmg_gb_w", 25],
 	["cup_b_uaz_mg_cdf", 25],
 	["cup_b_uaz_mg_acr", 25],
 	["cup_b_uaz_ags30_cdf", 25],
 	["cup_b_uaz_ags30_acr", 25],
 	["cup_b_uaz_spg9_cdf", 25],
 	["cup_b_uaz_spg9_acr", 25],
 	["cup_b_uaz_metis_cdf", 25],
 	["cup_b_uaz_metis_acr", 25],
	["cup_b_brdm2_hq_cdf", 50],
 	["cup_b_brdm2_hq_cz", 50],
 	["cup_b_brdm2_hq_des", 50],
 	["cup_b_brdm2_cdf", 50],
 	["cup_b_brdm2_atgm_cdf", 50],
 	["cup_b_brdm2_cz", 50],
 	["cup_b_brdm2_cz_des", 50],
 	["cup_b_btr60_cdf", 50],
 	["cup_b_bmp2_amb_cz", 50],
 	["cup_b_bmp2_amb_cdf", 50],
 	["cup_b_bmp2_amb_cz_des", 50],
 	["cup_b_dingo_cz_wdl", 50],
 	["cup_b_dingo_cz_des", 50],
 	["cup_b_dingo_ger_wdl", 50],
 	["cup_b_dingo_ger_des", 50],
 	["cup_b_dingo_gl_cz_wdl", 50],
 	["cup_b_dingo_gl_cz_des", 50],
 	["cup_b_dingo_gl_ger_wdl", 50],
 	["cup_b_dingo_gl_ger_des", 50],
 	["cup_b_mastiff_hmg_gb_d", 75],
 	["cup_b_mastiff_hmg_gb_w", 75],
 	["cup_b_mastiff_gmg_gb_d", 75],
 	["cup_b_mastiff_gmg_gb_w", 75],
 	["cup_b_mastiff_lmg_gb_d", 75],
 	["cup_b_mastiff_lmg_gb_w", 75],
 	["cup_b_ridgback_hmg_gb_d", 50],
 	["cup_b_ridgback_hmg_gb_w", 50],
 	["cup_b_ridgback_gmg_gb_d", 50],
 	["cup_b_ridgback_gmg_gb_w", 50],
 	["cup_b_ridgback_lmg_gb_d", 50],
 	["cup_b_ridgback_lmg_gb_w", 50],
 	["cup_b_wolfhound_hmg_gb_d", 75],
 	["cup_b_wolfhound_hmg_gb_w", 75],
 	["cup_b_wolfhound_gmg_gb_d", 75],
 	["cup_b_wolfhound_gmg_gb_w", 75],
 	["cup_b_wolfhound_lmg_gb_d", 75],
 	["cup_b_wolfhound_lmg_gb_w", 75],
 	["cup_b_rg31_m2_usmc", 25],
 	["cup_b_rg31_m2_od_usmc", 25],
 	["cup_b_rg31_m2_gc_usmc", 25],
 	["cup_b_rg31_mk19_usmc", 25],
 	["cup_b_rg31_mk19_od_usmc", 25],
 	["cup_b_rg31e_m2_usmc", 25],
 	["cup_b_m1133_mev_desert", 50],
 	["cup_b_m1133_mev_desert_slat", 50],
 	["cup_b_m1133_mev_woodland", 50],
 	["cup_b_m1133_mev_woodland_slat", 50],
	["cup_b_bmp2_cdf", 50],
 	["cup_b_bmp_hq_cdf", 50],
 	["cup_b_bmp2_cz", 50],
 	["cup_b_bmp2_cz_des", 50],
 	["cup_b_bmp_hq_cz", 50],
 	["cup_b_bmp_hq_cz_des", 50],
 	["cup_b_lav25_usmc", 50],
 	["cup_b_lav25m240_usmc", 50],
 	["cup_b_lav25_hq_usmc", 50],
 	["cup_b_m1126_icv_m2_desert", 50],
 	["cup_b_m1126_icv_m2_desert_slat", 50],
 	["cup_b_m1126_icv_m2_woodland", 50],
 	["cup_b_m1126_icv_m2_woodland_slat", 50],
 	["cup_b_m1126_icv_mk19_desert", 50],
 	["cup_b_m1126_icv_mk19_desert_slat", 50],
 	["cup_b_m1126_icv_mk19_woodland", 50],
 	["cup_b_m1126_icv_mk19_woodland_slat", 50],
 	["cup_b_m1130_cv_m2_desert", 50],
 	["cup_b_m1130_cv_m2_desert_slat", 50],
 	["cup_b_m1130_cv_m2_woodland", 50],
 	["cup_b_m1130_cv_m2_woodland_slat", 50],
 	["cup_b_m1135_atgmv_desert", 50],
 	["cup_b_m1135_atgmv_desert_slat", 50],
 	["cup_b_m1135_atgmv_woodland", 50],
 	["cup_b_m1135_atgmv_woodland_slat", 50],
 	["cup_b_m1128_mgs_desert", 50],
 	["cup_b_m1128_mgs_desert_slat", 50],
 	["cup_b_m1128_mgs_woodland", 50],
 	["cup_b_m1128_mgs_woodland_slat", 50],
 	["cup_b_aav_usmc", 50],
 	["cup_b_fv432_bulldog_gb_d", 50],
 	["cup_b_fv432_bulldog_gb_w", 50],
 	["cup_b_fv432_bulldog_gb_d_rws", 50],
 	["cup_b_fv432_bulldog_gb_w_rws", 50],
 	["cup_b_fv510_gb_d_slat", 50],
 	["cup_b_fv510_gb_w_slat", 50],
 	["cup_b_fv510_gb_d", 50],
 	["cup_b_fv510_gb_w", 50],
 	["cup_b_m113_usa", 50],
 	["cup_b_m163_usa", 50],
 	["cup_b_mcv80_gb_d_slat", 50],
 	["cup_b_mcv80_gb_w_slat", 50],
 	["cup_b_mcv80_gb_d", 50],
 	["cup_b_mcv80_gb_w", 50],
 	["cup_b_m2bradley_usa_d", 50],
 	["cup_b_m2bradley_usa_w", 50],
 	["cup_b_m2a3bradley_usa_d", 50],
 	["cup_b_m2a3bradley_usa_w", 50],
 	["cup_b_m7bradley_usa_d", 50],
 	["cup_b_m6linebacker_usa_d", 50],
 	["cup_b_m6linebacker_usa_w", 50],
 	["cup_b_zsu23_cdf", 50],
	["cup_b_hmmwv_unarmed_usmc", 25],
 	["cup_b_hmmwv_unarmed_usa", 25],
 	["cup_b_hmmwv_transport_usa", 25],
 	["cup_b_hmmwv_terminal_usa", 50],
 	["cup_b_hmmwv_ambulance_usmc", 50],
 	["cup_b_hmmwv_ambulance_usa", 50],
 	["cup_b_hmmwv_ambulance_acr", 50],
 	["cup_b_lr_ambulance_cz_w", 50],
 	["cup_b_lr_ambulance_cz_d", 50],
 	["cup_b_lr_ambulance_gb_w", 50],
 	["cup_b_lr_transport_cz_w", 25],
 	["cup_b_lr_transport_cz_d", 25],
 	["cup_b_lr_transport_gb_w", 25],
 	["cup_b_lr_transport_gb_d", 25],
 	["cup_b_uaz_open_acr", 25],
 	["cup_b_uaz_open_cdf", 25],
 	["cup_b_uaz_unarmed_cdf", 25],
 	["cup_b_uaz_unarmed_acr", 25],
 	["cup_b_mtvr_usa", 75],
 	["cup_b_mtvr_usmc", 75],
 	["cup_b_ural_cdf", 75],
 	["cup_b_mtvr_ammo_usa", 75],
 	["cup_b_mtvr_repair_usa", 50],
 	["cup_b_mtvr_ammo_usmc", 75],
 	["cup_b_mtvr_repair_usmc", 50],
 	["cup_b_ural_repair_cdf", 50],
 	["cup_b_ural_reammo_cdf", 75],
 	["cup_b_ural_open_cdf", 75]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
    
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
    
];
